apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: default
spec:
  encryptedData:
    api-token: AgAGdBl+Vajv7rG8NzjQNYBvVT6LH/wXXf7kpRKPJ5Ue3d7oa8y8vcu7OVwSzygwSornnbHfY56ts9IL3A8gOPNj3RAsrKcacDvqPEfGDxrH0cz6++F+O5iXBC5mT2/N3dWo2Z2w9FAOxjQzdMgdnGC1Rxl5loBEP8R55RYOfTy/RRZrVeH/fv1Gw3zlvRiHdGQRu4/mUb1w262/pHiqyzV85wV5YDlYVBUoLWiO0d6aj9zVyq4Na9JDKj1geyO4+MQX0col09Ou8bPdo1vRKG5uN2AWviZ+xS3tPu1I9vHbVsK+zFfJAMqhBNcK0JTkANxgOzNxPVlhkLeKAhSZgfn8O9wYEQRaIMeAhmOqwOiO0KwrFhqCPDn7D3Gp4z/c8xfNd7MKe6M54yla+MJJKTcPYgHYh7EMX8kbp8rdsRCvKg9fFzwU/HYtt7ocis4zxKlPb1g8h2+wlQESbmb1LEpGZz+atoEp6q+jMCe7Qorv/QMbuPKaPBA7tmuiyyYgy9jGMXZ21X8i+lzggf4ycXikLnQ3j4a1T3IRakSxE8LwFMHKkixyGvdGilyUPw4YpDXsaV5S3EBTvmOfHgTfygeAyssIqYbxDceR2MujYONpbRXQgHklNJ9BP0/nmXuxkis2GUhAETMAS+MGLf5fO3x/Wn1bjehqzOQXm2m3/Z3NwCSBGL+6H61gLN19zSwMGslo4qaRjSIkSSql8g9JApBoDD/eVCNFOo9ApxX2E6pfFD6GUZeqQfhN
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: default
    type: Opaque
