apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mk@maero.dk

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production

    # ACME DNS-01 provider configurations
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          email: mk@maero.dk
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
