nats:
  config:
    # cluster:
    #   enabled: true
    #   replicas: 3
    max_payload: 16Mi

    jetstream:
      enabled: true

      memoryStore:
        enabled: true

      fileStore:
        pvc:
          size: 20Gi

  container:
    # env:
    #   # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
    #   # should be ~90% of memory limit
    #   GOMEMLIMIT: 7GiB
    merge:
      # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
      resources:
        requests:
          cpu: "2"
          memory: 8Gi
        limits:
          cpu: "2"
          memory: 8Gi

  podTemplate:
    topologySpreadConstraints:
      kubernetes.io/hostname:
        maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
