nats:
  config:
    cluster:
      enabled: true
      replicas: 3

    merge:
      max_payload: 16000000

    jetstream:
      enabled: true

      memoryStore:
        enabled: true

      fileStore:
        pvc:
          size: 20Gi

  container:
    # env:
    #   # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
    #   # should be ~90% of memory limit
    #   GOMEMLIMIT: 7GiB
    merge:
      # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
      resources:
        requests:
          cpu: "1"
          memory: 256Mi
        limits:
          cpu: "1"
          memory: 1Gi

  podTemplate:
    topologySpreadConstraints:
      kubernetes.io/hostname:
        maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
