nats:
  config:
    cluster:
      enabled: true
      replicas: 3

    merge:
      max_payload: 16000000

    # Enable metrics monitoring.
    monitor:
      enabled: true

    mqtt:
      # Enable MQTT service.
      enabled: true

    # Enable JetStream.
    jetstream:
      enabled: true

      memoryStore:
        enabled: true

      fileStore:
        pvc:
          size: 20Gi

  container:
    # env:
    #   # different from k8s units, suffix must be B, KiB, MiB, GiB, or TiB
    #   # should be ~90% of memory limit
    #   GOMEMLIMIT: 7GiB
    merge:
      # recommended limit is at least 2 CPU cores and 8Gi Memory for production JetStream clusters
      resources:
        requests:
          cpu: "1"
          memory: 256Mi
        limits:
          cpu: "1"
          memory: 1Gi

  natsBox:
    # -- Disable deployment of the nats-box pod.
    enabled: false

  # Enable prometheus metrics monitoring.
  #
  # Note: requires `config.monitor` to be enabled.
  promExporter:
    enabled: true

    # Create the PodMonitor resource since we already use prometheus operator in
    # the cluster.
    podMonitor:
      enabled: true

      # Add the pod monitor selector label so our prometheus instance discovers
      # the podmonitor.
      merge:
        metadata:
          labels:
            metrics.uplink.io/monitor: prometheus


  # Limit deployments to 1 instance per node.
  podTemplate:
    topologySpreadConstraints:
      kubernetes.io/hostname:
        maxSkew: 1
        whenUnsatisfiable: DoNotSchedule
