---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-auth
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgBpMHFtyP7h1zAsXdm0bw8fvYB8+eGN7kvdm60qZLhIT/+eylhULd2/yu2wVU2OE5/KUBsnTn5y/6vNHIaWm35OdM2WljTR0uWsfTcohFCgNAJW7YYaOHPJCIPkIqY5BsU2BYaomy7A+UfeO1Kw2xye4mUyz2JYFZHstYh6v/F/uZw1mq0JmYWOHSEk0G8H7R67uS3xOxwvrOQwy3cuHFf0Nz/MVjPHEnPutyesZ16wLdofnLQ+To4Qv1HAScq7fKO7aqExCEqYXVXs7B+8Xncw+svUjsM4XcGbGH03kkGeAb2Jpx4beuQ3H21nttwU+GiFB0r1IyDJN8HRkXKwS6LBX4T1fVW9MeEs510se7pY93jZAKYuk8s3yJ21OWxqx5u8TzpPYsUAtx1eAxECJ8hU793/x4daznQ5i2hLdIPjxKf7LxTaLKmJuyyTahNSoPFFxx2WNmYX50BC72Ejuh252LmSaRWEeVTNzFqNKK9N4pjSwm8t+V5C/P5sUlojplGKu5/pVATP6dKsbEk0rFcIadRYhPpYjl/66eVA50nLHGiwXqIjvUW9lkrbeDAQ+WFI8Zgm3kvNyeyNLxAndB34QNq7EG9NiTJIfoha209nhkcg8vVKOr8sxl/wEllNeq/VQd97edCek3zqYYICQ1ZkTIl7GZLz5EMoN8spwMOEZcE0qfCobW8AqWNSOfw7aco2KujNuMdAsVJVEtGw1hjehYcPAuBOWdAf05366Z2+nw==
    admin-user: AgAeVGsxPn0hNrAO9+PVWaAV//vzjO/TN4mwn2PX+U9BSmeqfLUKqAH6H0NQyaHEouXxhp2CDI1i9Nsq466QWEuxpAddPzKKByppZCBh1zZPkzJqxqVoQBpmDphUaOSplxApMyXGl15HZWArzGa712wZUd/aOqOyxAMqBOh8VivYxXoIRkcYUyDsjC45x1qha+G/TZj1YCD5XwWzA24RTOXaiP5Bg7jPQfDJ+T4hfkymMqbBCFiGuE0k55rRk3mBVP+nl35z2yyhfHLvn3ijTAd2Y3YUYKzy7jbARd5zMTh528Tprzp0tDgoxEAYUBikE2KC6KljnghujJU9I1XEW1HbYhIAWXRjmYyyEh8o2D0HKPgG4PIioe61+plR6cLGmJfWeej2LrgCuwgCe9d6SJ8DnkSLFXBDdcfDCzV4JFRbu0r/w1eUKf4F0SVgAdsJkLDgwaEcJbHpbPEvO+ataEWMJV3HQVLt80AroiYqTQPRIBs1VNUQ0ZY0gPzX3htRoiBtHziqrFEcjM4/D50UoJLzGINlaz5AcTRTlhuFn0TwRZA5z76l/IZow5FQww3sBxzzVVFXeE4kdev81qAaUhicp75ne8C/T/AHH+UANvJyjEKbtQEp6GBzjD8wHpUT+y0c1vyyC6piaU1APZoNuRbLC5fIKNO/3BIHjKqleAJrMNAYBs+vpgaS8fNVKXGubFmCV5GwKA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-auth
      namespace: grafana
    type: Opaque
