---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-auth
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgCc0cqeFwPGNreh74t6VFp9DMfRXgqizZ1Mr6Pl02plZo477ZAqhgjLpl71cCTPd8qYQXrJKQtNMPZf4uDOaOKZtzHzDNNZfxQWN8XzNMyEBHX3/63efHS29UuxdP4C11Wc16aZyzMIFk0QUqfKWCZyIpZupU6iEsX/9jIPqqbbnQEWNFz1DKgRVs9nuVSClo0yzwRUcSsn9FRQa+BJnNqz2IJOiGqYCzYgTQQ2ThgeBefRSxj1xvK52IUuR7KvDyZe4VJDLEDJhsoVBUA/80d8Xz/iCcJsBOuWZGvJAkOW9XyUzPYseCmdCrLylSKefvWBPZX6KA/vDJ7YWfQybpkmC5R0J7wBsl2H3u/Gjj8+Zkse1w1gbBW85YBovXXrTAhiJ+nHNx29VcCBDCvibqnLtE4gJ+3DJnXWds5wzkHemn8V6UGv1duZQGkdvKquZAbCV5t5LFm3Z0mmF5da4l35at1PF4PNX17bdR1QZ+wSdo9Ej9YA8PqjAbb6W5kYlsbieM1X9e6AW2njyCzxJURUdzkm9oq+pgPeeXe6SnNYlJ/WFU2fFHxvORA2aYprM7H0JQwMid9omVZJYN5IlnSg8FXjw9ODjY0DfVmgAtphfDJOTOeL5bSxdsp+fd4l8iCUDqmI4XfJJwmG/zvp0vHnfsc3SGlUk+FqSrQlxa0tgvQx4nBBADPY7MqJsjzHjrZNnzC5pcHt7z+1mNAORF+A6tJCuVfm0l4yrkPrLstj0w==
    admin-user: AgBOZ+NUZkbjuJnUTchTeQhA0Mct0UTyP6qqVk3jxgjx3oe4/UQqm7I81QpdaHdzIw/H4SgMdSHqXquOXX2D7mTN12nFtjMe69y690i0zYjzBchSPgcitaKvPp5iOIZC4Q+cPa7PoJl9tUCaykRvuk+du6pQvCXbJaur24Ku01L6rnlWwNQ7DIDy7EAD7C0yzGOpwD5lvWhot1X1oC524NSCOL5SVHYl/oLVaC7qWfHB+RZuI4zQh1ZREZiN2VrIuqeCzWsmltsGNtajGhqN8rxcarE8GnWyktPv5rDUfT/+TdFkYqWaukGN61HpbFFhqqwPa6g6OkTUNvNZDTcC0EMwWrKaq/T0J2TmhUkoG9u7f6EtqZCuTc3AHxS/waTfUL7/FKQdURMveAFQEDvmAZMEeDLcGHPncGb03zVoQ/pNDZYV5HsZVzfV6RqjDanP5GXL9tnxj+1gjCUzC0XWW3kNZu+CSR3yh8eSa4jxdld7ob/+ZdOS6loaqmNPOGWU+9upJ7rbZCq2a1gA4LdPKbU9BzhCrUbbE58GYgyxYTt6khFY1IHj8juNxHR5yJLtPN/tlwatkT5Bd6j4wtXZxz/svmeNaTxok5Eui33AnFTcPFig0O0CY6Il6c5Ush4XfO47f6kvkhh93FH2OaFJ9PZGePoQwTEiRQC05Jl4mbSK2u4HR3ohVZNiE/cwWHJFqarqGhbKvA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-auth
      namespace: grafana
