apiVersion: v1
kind: Service
metadata:
  name: nats-mqtt
spec:
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/component: nats
  type: LoadBalancer
