longhorn:
  image:
    longhorn:
      engine:
        repository: longhornio/longhorn-engine
        tag: v1.5.1-rc1
      manager:
        repository: longhornio/longhorn-manager
        tag: v1.5.1-rc1
      ui:
        repository: longhornio/longhorn-ui
        tag: v1.5.1-rc1
      instanceManager:
        repository: longhornio/longhorn-instance-manager
        tag: v1.5.1-rc1
      shareManager:
        repository: longhornio/longhorn-share-manager
        tag: v1.5.1-rc1
      backingImageManager:
        repository: longhornio/backing-image-manager
        tag: v1.5.1-rc1
      supportBundleKit:
        repository: longhornio/support-bundle-kit
        tag: v0.0.25
    csi:
      attacher:
        repository: longhornio/csi-attacher
        tag: v4.2.0
      provisioner:
        repository: longhornio/csi-provisioner
        tag: v3.4.1
      nodeDriverRegistrar:
        repository: longhornio/csi-node-driver-registrar
        tag: v2.7.0
      resizer:
        repository: longhornio/csi-resizer
        tag: v1.7.0
      snapshotter:
        repository: longhornio/csi-snapshotter
        tag: v6.2.1
      livenessProbe:
        repository: longhornio/livenessprobe
        tag: v2.9.0
    pullPolicy: IfNotPresent

  defaultSettings:
    backupTarget: s3://mkroman-backup@eu-central-003/
    backupTargetCredentialSecret: backblaze-b2
    defaultReplicaCount: 2

  persistence:
    defaultNodeSelector:
      enable: true
      selector: "storage"
