apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argo-cd.infra.rwx.im

  # Disable the admin user.
  admin.enabled: "false"

  # Enable application status badge feature.
  statusbadge.enabled: "true"

  # Configure Auth0 OIDC authentication
  oidc.config: |
    name: Auth0
    issuer: https://rwx-prod.eu.auth0.com/
    clientID: wicwEMz2ohytCLBZVGSLMaSgVc1nzzIM
    clientSecret: $oidc.auth0.clientSecret
    requestedScopes:
    - openid
    - profile
    - email
    - 'https://rwx.im/claims/groups'
    logoutURL: https://rwx-prod.eu.auth0/oidc/logout?id_token_hint={{token}}&post_logout_redirect_uri={{logoutRedirectURL}}

  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
       - CiliumIdentity
      clusters:
       - "*"

  # Health status for cert-manager certificates.
  resource.customizations.health.cert-manager.io_Certificate: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Ready" and condition.status == "False" then
            hs.status = "Degraded"
            hs.message = condition.message
            return hs
          end
          if condition.type == "Ready" and condition.status == "True" then
            hs.status = "Healthy"
            hs.message = condition.message
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for certificate"
    return hs

  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'

  resource.customizations.ignoreDifferences.apiextensions.k8s.io_CustomResourceDefinition: |
    jqPathExpressions:
    - '.spec.conversion.webhook.clientConfig.caBundle'

  resource.customizations.ignoreDifferences.metallb.io_IPAddressPool: |
    jqPathExpressions:
    - '.status'

  resource.customizations.ignoreDifferences.metallb.io_BGPAdvertisement: |
    jqPathExpressions:
    - '.status'

  resource.customizations.ignoreDifferences.metallb.io_BGPPeer: |
    jqPathExpressions:
    - '.status'

  resource.customizations.ignoreDifferences.cert-manager.io_Certificate: |
    jqPathExpressions:
    - '.spec.duration'
