namespace: rwx
resources:
- base/persistentvolumeclaim.yaml
- base/service.yaml
- base/sealedsecret.dendrite-config.yaml
- base/sealedsecret.dendrite-appservices.yaml
- base/sealedsecret.dendrite-signing-key.yaml
- base/deployment.yaml
- base/ingressroute.yaml
