namespace: rwx
resources:
- base/persistentvolumeclaim.yaml
- base/service.yaml
- base/cluster.postgres.yaml
- base/sealedsecret.postgres-superuser-auth.yaml
- base/sealedsecret.postgres-dendrite-auth.yaml
- base/sealedsecret.postgres-backup.yaml
- base/sealedsecret.dendrite-config.yaml
- base/sealedsecret.dendrite-appservices.yaml
- base/deployment.yaml
- base/ingressroute.yaml
images:
- name: matrixdotorg/dendrite-monolith
  newTag: v0.13.4
