namespace: rwx
resources:
- base/persistentvolumeclaim.yaml
- base/service.yaml
- base/sealedsecret.dendrite-config.yaml
- base/sealedsecret.dendrite-appservices.yaml
- base/deployment.yaml
- base/ingressroute.yaml
images:
- name: matrixdotorg/dendrite-monolith
  newTag: v0.9.5
