namespace: rwx
resources:
- base/storageclass.yaml
- base/persistentvolume.yaml
- base/persistentvolumeclaim.yaml
- base/service.yaml
- base/sealedsecret.yaml
- base/postgresql.yaml
- base/deployment.yaml
- base/ingressroute.yaml
