namespace: rwx
resources:
- base/service.yaml
# - base/cluster.postgres.yaml
- base/scheduledbackup.postgres.yaml
- base/sealedsecret.postgres-superuser-auth.yaml
# - base/sealedsecret.postgres-dendrite-auth.yaml
- base/sealedsecret.postgres-backup.yaml
- base/sealedsecret.dendrite-config.yaml
- base/sealedsecret.dendrite-monitoring-auth.yaml
# - base/sealedsecret.dendrite-appservices.yaml
- base/deployment.nginx.yaml
- base/configmap.nginx-config.yaml
- base/service.nginx.yaml
- base/deployment.yaml
- base/certificate.yaml
- base/ingressroute.yaml
- base/servicemonitor.dendrite.yaml
images:
- name: matrixdotorg/dendrite-monolith
  newTag: v0.15.2@sha256:7dafe6edfc8cfab758a68a4cf20414df1ade4a36b45b1852554d81fb70b1272c
- name: nginx
  newTag: 1.29.1@sha256:d5f28ef21aabddd098f3dbc21fe5b7a7d7a184720bc07da0b6c9b9820e97f25e
