resources:
- ./cdi-operator-1.62.0.yaml
- ./cdi-cr-1.62.0.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cdi-operator
    spec:
      template:
        spec:
          containers:
          - name: cdi-operator
            env:
            - name: DEPLOY_CLUSTER_RESOURCES
              value: "false"
  target:
    group: apps
    version: v1
    kind: Deployment
    name: cdi-operator
