apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thanos-store
  labels:
    app.kubernetes.io/name: thanos-store
    metrics.uplink.io/monitor: prometheus
spec:
  endpoints:
  - interval: 30s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-store
