apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-compact
  labels:
    app.kubernetes.io/name: thanos-compact
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-compact
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-compact
    spec:
      containers:
      - name: thanos-compact
        image: quay.io/thanos/thanos:v0.37.2
        args:
        - compact
        - --log.level=info
        - --wait
        - --data-dir
        - /data
        - --deduplication.replica-label=prometheus_replica
        - --objstore.config=$(OBJSTORE_CONFIG)
        - --retention.resolution-raw=0s
        - --retention.resolution-5m=0s
        - --retention.resolution-1h=0s
        env:
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-storage
        livenessProbe:
          failureThreshold: 4
          httpGet:
            path: /-/healthy
            port: 10902
            scheme: HTTP
          periodSeconds: 30
        readinessProbe:
          failureThreshold: 20
          httpGet:
            path: /-/ready
            port: 10902
            scheme: HTTP
          periodSeconds: 5
        resources:
          limits:
            cpu: 0.42
            memory: 420Mi
          requests:
            cpu: 0.123
            memory: 123Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: thanos-data-dir
          mountPath: /data
      volumes:
      - name: thanos-data-dir
        emptyDir: {}


