traefik:
  instanceLabelOverride: traefik

  deployment:
    # Use a DaemonSet deployment so every node can take http traffic
    kind: DaemonSet

  ingressClass:
    enabled: true
    isDefaultClass: true

  service:
    spec:
      # Use a static ip address so we can port forward it
      loadBalancerIP: 10.0.1.128
      # Use a local traffic policy so we can get the users origin ip
      externalTrafficPolicy: Local

  providers:
    kubernetesCRD:
      enabled: true
      # Allow IngressRoutes to reference resources in other namespaces
      allowCrossNamespace: true

    kubernetesIngress:
      enabled: true
      publishedService:
        # -- This is used to determine resource health
        enabled: true
