apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin
          subPath: argocd-vault-plugin
        envFrom:
        - secretRef:
            name: argocd-vault-plugin-credentials
      volumes:
      - name: custom-tools
        emptyDir: {}

      initContainers:
      - name: download-tools
        image: alpine:3.15
        command: [sh, -c]
        env:
        - name: AVP_VERSION
          value: '1.9.0'
        args:
        - >-
          curl -s -L \
            https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 \
            -o argocd-vault-plugin
            chmod +x argocd-vault-plugin && mv argocd-vault-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
