apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    metrics.uplink.io/monitor-instance: default
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    prometheus.prometheus-operator.dev/instance: prometheus
