apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    metrics.uplink.io/monitor: prometheus
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
