apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-auth
  namespace: redis
spec:
  encryptedData:
    password: AgAWrQlpwjKjZalsLbeWQGbmKsMZDEV6gutDU0FmaLMlQLPRCiu76xC30bTo4MqT920z8t8gYWLAG1pMKUR3/5ZnPlow/GAu3DJAopigDBj6sf7z488NIwtBoV4npMHQ40ZVCuwvOwXWwn6+YOiBXvFfl0+sE+dgQ/ZbWSCDSmsNKUG3hxmoShph8JyBn3qC2uV6+m/FepLqpgf2fPZHuNOjAGilNUR2Xc5krcphxowR9AGXJtfwfWeNMKuM2mSo8WEpR6WSOE/d1uXzM6lE9VCW6N8Z4/QMSRAmTw4ycKoVrHoeOGlDQzhhjjVpl7nq9UWn8rl8iKaYqc+NmGiy/S7vCATMPctjsPEesnz+22AwD9DMzpT8sOIj14lR7V5d/0glvftPSsX7DvXDO9qQ+O61bZAKjm7bOHr9/d8PIouQYXd5+cNq9WS6qyerrhYs0S5s/ZpTJ5faFOIUA0g6OKCoy3U4zTejyy+mCwWiXQB1wjK4dUmhdpQg7Zxu+TQWC4LGf0wI3X+hC2lXG8TQyy6ER8ZE/ln6cHGM44k+YjNhqgPO1cY/RdKxbuVOpQxNPRuTt7yfaqckcitn6xfgzcsF0Nisnl991l8kA1p6P+zCq+qJd730EMQAzqtOJOjKW4jtauOJYK87puRJSZcJcgjVSZIFnmZH2yo4C11IeHQcAYmrN8CZGb5PpFiGV9UvyU9331DsIQGcvWGwXwC0HAsGivyphLWrhMtZ49o/99QODA==
  template:
    metadata:
      creationTimestamp: null
      name: redis-auth
      namespace: redis
    type: Opaque

