---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-server-http
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`vault.infra.rwx.im`)
    middlewares:
    - name: redirect-to-https
      namespace: rwx
    services:
    - name: vault
      port: 8200
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-server-https
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`vault.infra.rwx.im`)
    services:
    - name: vault
      port: 8200
      scheme: https
      serversTransport: vault-transport
  tls:
    secretName: infra-rwx-im-tls
