---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-basic-auth
  namespace: monitoring
spec:
  encryptedData:
    password: AgBOndLm6phI8swWc5vb7Q2Dh3AGHn8auMY36cRZc6DryqliWBkhtsNKQkC/CI2NuATU8c0jYUH0qa2fjG46OHpc34O+t1UEfeO630/+CIE0VsjPHaCRU2OFihl9YMhTHx5cWcb0/Qe+xmz+ISAWRGXOG1M98Zbe8sy8JkeeJ20P1ick0HEFmRRX47SohOLFx7lK5kK/KbkTwy+3QDy+RoYw2V/EtWx4vZ1vClYqzhx0SMhmQg5GgP9IrLJM9wcenUOyqq/EFnKKhS2nuF4uKqEhWyo/PilcMEgykkq34DY6jsszFMriXfGENU8Ii95tDf12+WzOWAh5XPPUILAmTiLp6t78/Dls3HiDSjCH2Rdcv4ZB3ReGfC9COThp124UAaMIikBEtsgRWsaCRcmIUztc8uMjG4NIBNjQCDal5R327OWgKAMBkJuCShbkiFyr7iyypbhxa/RGVEiKDS92kYByrJwa2hYlx/Q3cgqEiXnylL1o6RAH5+8mb15Aye6XK6d8nqyMcNoWypblyJ5besKb2fV0I/UnSeBtvJnrvkde7/QewVsIsP4Y6cRQsysdXIDivM/rBxAo+ecgRPf05ifB7oy9JTppJC3bFQZ06Ft+gh7sSMUKDmgr0ZItzpCQnxaDgZEG+fUrF/T2i6FLzZ71hgVXdNjzaMsNF8Y/xbasStKNkn+/KiBSDh0kfcktlCSki5gToaRw7XpupDiyIPsXNja7NYA4tcbPw8S1Bqb33A==
    username: AgA78mYN/wexetCuBHM3Nno2JKTcNT69vxPyhjm4F7+tjs9YEDCz7S4M5qeN8yvP0R2IACgLTZY60KyDhhW2L+222hc3T0ibrckPERUehr9YUL54b5gaAAuVExGQjlun50xACH4CHJiai+pHdaoBCLBSJroxLTLcNokWQ4zfLkuiP57HAJhkM/QBfENFlfQzmeTGuCQN9638mXc4g1FRaH+pv3d1FHIjlHzZ32txMRJSgP5V5em6pzdxQO6o01tLjm+H1/cXzf+CNfcsErAnUMmKORhy+5GzRDpLhDeWPVWfjsV5Kj9NNQdw23EdAfdr9RrTdwIjfv/uuuekYenGPJX3lR6OTw02DQAQt3iOHAM8aauDNB4v+1xgDRIw6K+/eeeir7oZafmvXo3VqhRGcnmhTVVpnkVTKnP3MqOIsV1MAu79yeSVvxJM4a9idOsLNeIoSgUvgAIMN464R5W/waOcd9wjj7/ahgFU3r93oil7V1DXJ7m7VNQ0ULWI7LCdNNp8ynCDWEg+Oi03anz9AV4ed4fepKXGk38jD5ZsoyPNkE5fT9HVrMuGpGNBIx5ruL1oTCCnySdhs8DctfvizGXvQUI5bUm9pbAWgc8qCBVK12ulqESoFIlvCm0ZBLtmLvhy6zfkP5XMJVEJ1ESxC36RywOK0Vk/Dv8CeUkMNaYOZnr7wMKxzBAdHojOOgQw+IQOJQ==
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-basic-auth
      namespace: monitoring
    type: kubernetes.io/basic-auth
