---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgByfTYx148f7pRdc2oKMh7O/rwB483eCHLU4x+Jjr+kHpjRr9yh7M94RHlFmWL83V5H0tgJTbufBMw7GNBD9jDsUFz21+EjPNMl+GL18s31Z/DRGmJBngEJRpIM2zX27rHnDlUi8EAWI8PZaEfUX2eEP/0eOm8Wm3w/r2d1Sa3Wo7t0FiIbwJvXgB8tdW4d3tzOg/JteexNIV0G+GLXQLcUx2EEd4HDe0+5FzAIeELSLprZbR0dyBdMYvgIxzmELkYpG5U8PX2sDseVaPX18CJxkUqLJJ3f/056RmJQsDyg4Pie1xySP25NSdx0RMKO6OdiPW7HsXAVqnj0yxTfv3qR4uAvRnIDVcU/9vEP0yDTzlZN+C5iTZlvP9dXWJQDRKYXr2CckAxm0PPk2x4CXCAddWYDCBwLTMRNvGJMOrAAm0RlawX6qB8Yc+NJBa2OQt+tLasXRBvS3ClatDSNqiUgZCmPFkfBsGXJ6pmBaRkDrwlZrzknMQmb20E/mE9Um+DZ3D76CkWU5BWZXcRKgIExJS+779OYMgcZTK6KTHMtxN6RjLQD/McdS7DWRuC8S1nhrKCL19Ie0rczwqVVaTEEF8fMTrHO9a/ozS+Iodve5EjGiGXYq9OHC7KK97nKWgw8+JBeQ/yo+SydZD2mVuJVI/EFPA+KG5r0rreNcyl0yLvunJviTdOHlr9kCnSNOeNRXrkbMAI/4E6XQegmYxLoKh8pv+cYORg6bVaOUWfroQ==
    username: AgAyyoro3z74zMC+nGIQk1XCXpNLmTJ3fwBJBxS/Tu9OCLlGDNT0NebRTiAs9w9/p+zCK48O8HhpsZjsIbp7NoIsLufHN1jhT9wKw0KOnI8Z9eNHnvWmVB5hYuwB2SHd/r7nDhMZjfE9IJRfcZE/vd23a8U4Hi5/0MsW+urEOs1yH4BInUjFDZt5aHWN2+Uiqp71GZOC9Q7+/Eu6ULlCzbOsEi8IGjzy0yAWSXhh5w9vCKrmIDEPHifWXP2sCT+btx2nLXMIoI+5tP1KMrcbfPRBfXK+LTK6Zd/FmI6tUbmGXz2DioVStm8avxRc4FdEe9g9OjnySuUPbSAlNKEGZygnSl+IIcRrpD9qcTnHKtb2B6CWZtCgFV3R/Pfob0To9+GQ0En0FKOQtFz39wRgEkF11YGkusdbrv68apUV0y73IFGltq3xVszx577XW6QPu3gOA9zmh6GjdCxWkGqNtUPEOyjXSj5lepYXuQcriGRvqIs3vL8c7zELJsqODp3xplWZTnAfO5lgRcXZdU/xl8FspR+/sfM5CDbAZhVU2gHIZZOM5vr2cWK+2beAR5yRXljZpGU8652dPFC9JPj5hOHlggJBhvg7NsfXA+q8jh1seyxFXgMWfQzNZ7cKrScgULqbfU5DJ6HLWRzv9v5kpJDF8RF1MPbXwi47Gg9x2Rvb/5nfN4Qc4AD155tJ0QYinVyX+g==
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-basic-auth
      namespace: default
    type: kubernetes.io/basic-auth
