apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: matrix.rwx.im
spec:
  secretName: matrix.rwx.im-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - matrix.rwx.im
