apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:14

  backup:
    barmanObjectStore:
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      destinationPath: s3://dendrite-postgres-backup
      s3Credentials:
        accessKeyId:
          key: AWS_ACCESS_KEY_ID
          name: postgres-backup
        region:
          key: AWS_REGION
          name: postgres-backup
        secretAccessKey:
          key: AWS_SECRET_ACCESS_KEY
          name: postgres-backup
      # tags:
      #   backupRetentionPolicy: "expire"
      # historyTags:
      #   backupRetentionPolicy: "keep"
    retentionPolicy: "7d"

  superuserSecret:
    name: postgres-superuser-auth

  bootstrap:
    initdb:
      database: dendrite
      owner: dendrite
      secret:
        name: postgres-dendrite-auth
  # bootstrap:
  #   recovery:
  #     source: clusterBackup
  #     recoveryTarget:
  #       backupID: 20230617T011555
  #       targetImmediate: true

  # externalClusters:
  # - name: clusterBackup
  #   barmanObjectStore:
  #     destinationPath: s3://meta-postgres-backup
  #     serverName: postgres
  #     s3Credentials:
  #       accessKeyId:
  #         key: AWS_ACCESS_KEY_ID
  #         name: postgres-backup
  #       region:
  #         key: AWS_REGION
  #         name: postgres-backup
  #       secretAccessKey:
  #         key: AWS_SECRET_ACCESS_KEY
  #         name: postgres-backup
  #     wal:
  #       maxParallel: 8

  storage:
    size: 100Gi
    storageClass: ssd

  monitoring:
    enablePodMonitor: true
