---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dendrite
  labels:
    app: dendrite
spec:
  selector:
    matchLabels:
      app: dendrite
  template:
    metadata:
      labels:
        app: dendrite
    spec:
      containers:
      - name: dendrite
        image: matrixdotorg/dendrite-monolith:v0.5.1
        volumeMounts:
        - name: media
          mountPath: /var/dendrite/media
        - name: tls
          mountPath: /etc/dendrite/tls
          readOnly: true
        - name: config
          mountPath: /etc/dendrite
          readOnly: true
        - name: signing-key
          mountPath: /etc/dendrite/signing
          readOnly: true
        - name: appservices
          mountPath: /etc/dendrite/appservices
          readOnly: true
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: dendrite-media
      - name: tls
        secret:
          secretName: rwx-im-tls
      - name: config
        secret:
          secretName: dendrite-config
      - name: signing-key
        secret:
          secretName: dendrite-config
          items:
          - key: matrix_key.pem
            path: matrix_key.pem
      - name: appservices
        secret:
          secretName: dendrite-appservices
