---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-dendrite-auth
  namespace: rwx
spec:
  encryptedData:
    password: AgB6tFh9vyrsNL8jEBoGYih4efv7UKYB/dcrr7TVV91dzOc7p5rETLTD+7b/PrYjY92spTUHXrFc52T1qT6kG+8fycUZaF6HkH8jqasf+V3LEjJNt7exvieyxovI7x5nHCIvgpcnTBr6sNuzHXwFEao5uWPluMTb1RcGLQ60DbD6ySlUklwgQWlk4U3Wu1TeFk5UgvYC56wjhrZRfuxv92U3wIVnjWpoO4plEGswhOspBM2nyFDP38T1bWoJR3rqOWXQPDMGGGNJiHzDBEwM98E9t+Sri/3bz2C3Dsp1/5T7lfsoFkBRKgi4p5kY9AUemCkp5TRhtrws9d889jSxY13iGYlivL4VcD0c24ZGoeOSJ4xv9iqK0DR+JJWqw54SU3gezQZvmhRxsfizJvCb4Yd6iQJr8FQsZV5frOC6uu3gzU0f9fJ6jw5KDjz86aFwKYPcvkArXeu1/akH3GPi8RqyUCXrqbHqHYtoeK9hUKTSEikil1JjtiW1DPpUUdsgr1AJcSYzeCztKaiL1cOtmwQ/vJfnbYI6R+56WpB12vPgGTAhHaLopQwNa7Xz/vFGL2vvckhBaVIxgPr2ddn5OwKG4MqUj3Ko86K0OYNCOkpzrncYm6/Gju9Kt6rFczyaaJ6qUiv4o/bF9r0NesSJsY1kxvUrzHJ0e/IJJ8ASCRJj1tvCw+nUWQCpBJVJfiB/B1zYBmBHuED8EMydTujXUQEGz9CLs9L5tKlYvimSXEsjfFCU22A5YHRVncrFUF9gQkL18iK5Fx54NONRs5xK3DQE
    username: AgBl+Cc1IAQHf+4tYGQ15VqM9yuZXqFN4o+nELtMo8xADsq5p0Aw1Ia5vpKXGcR8AzbsoDGVyG8Pg8GPYtBdSDPBAHzzHkw1sqWWs9a8yvTQiNNjI7BL1xdswTHJ1IpFqfStYWaGgSWbkjtUE95GyFKTmbMQ8kMlnw00T9cdzTGyek/qOgEZS9E5EF8FAkUs/bXBq6klGV25gSIy/8TDrMa0fhYqtU3MOY8xEDQW3vFqYkbdZ/1UOySzWVb998weiP1Z5KiYncgIOeKXPsHgzQd5Ijuf82yLXXTVe4h8IT/iXEsQkzTghvrLN7GRQgZSugJv1Ou00xMyasN/zjQeCdWJG8Bv4Npb3CMnYdiq82H1q75y6Ab3+dwj8Ag7GMqExSVV/RZ2qp1XTwPSentlfGWkBreWF5rtvhuzH95vdRvEVUW1wpoJ7jsPFfD+hncQWNvbfudJ+W8koTFX85hYTg9hrE+z6cDO2zJZd1G6m+zUpPH9poSOiMAmUckvi7TnHiHWREwINKz3wMDmUc8sDcvOWyQ7Mr6UFVpL+qwrRLbOMKpAYCHIkeklTlQeRysV63KQo+J055hAeA6nF5N/0rdjhmeiRtlpwkjtTO33TTN4IqTaUlHJXW7DHzYglRJOkUy+nQLGO/g3uRQLJd1PTfJQ0R6Y+pjnEgeY1/auulutUO98DsAQiPhBS82pET/XlHN0heSkMPS6zg==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-dendrite-auth
      namespace: rwx
    type: kubernetes.io/basic-auth
