---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-superuser-auth
  namespace: rwx
spec:
  encryptedData:
    password: AgBZsX6ZVN8i7abM/qb3WEAoYj34FqgxW+18kLHGvoPfKkjj6k8EoZ5ZZgk41mbS/EOuGYC3HG2TsHUsv2Gzcb2Wvmu2vaKSrj2fqHZXwUaRGkDtHZxLvMBbYwa4/hFv6riwvc8G1PhdSwKMTg6XDKArRahRRRL5VKp75tdzniU4djVvahtAD45w2LYXKTID4DZIAGgxU1NYF/qmiM36rNWhkuPhVm76Zl2QszyzFkhbNo8YvOGbh470C7iNET0zhDeu7YYYbXVDyRz6E5vdagujFR4hbKntZGQ7CZxricRV8ZS5ndRHqhsBXz4MlTka/W8mvxMy1JaW/hNM4WK5EqLMuNdHOvRl9TGN+AnI7RFQ/of8XSPACreqHOHu8rgfyVh+CQMTpvh37Ubepl3nX8AzUnZ5vXvvw4cYXoUiiV4hGszkhdPGXPVpgfhZfxkoRjU2GvF0xoYMg0IVXEaI61NpR5B3Ju2ALMOzsbTeNskJOiY0sr5c+YIEKAQrvhuQ7GnzHyXPwvPoirKLtzDE4Q0HDwEkF3KBfyhVr6/fmoiP8C7XB28cXmH/kOPfFlrTfTL4CJeu9tjAYvMBPw9mnK1ROqzxQHm4mFkZlmBjBuGAZfoAYGkraT1RNsNqpw45UInBlFQzfL0TfBViFoz0NLTZwOTUBVRZF5JQVzQO8EcU6jpawRoZqfspSwpac8qKy2jJAm2QCUzXdAAVf51tb3SJ/sZ9dmd8lumyF7GtqxujD314sCACEjaoljMDI6VZD89tTZZaew9jFi0D4yRy
    username: AgCMyy9pxZv0ad5hR1MQjljDlgVCd1jNa17um1ND4/HuT+UvLsNRaiKPJyp0xZSdzo5ipb1cq0sBCBVZ3G+EOO/ZbtURJJr63aJTsLEUMnL1bIXNv4EoqOsVcUyO8kxvfhIQbRZZStyXVn5KxXe+ZQg2HziFpYSZQWwwg5+7ryrY9AbbWCIZgOwLwir5eTqxZpPFJWMS0qZHcgNjgb6hhxhfKjRZsM5oP7lCVJbQZsJxg43/DN5DA9XIAVIv7OAFqx8ndXU2stCqIL87cnj1oJfmdbLlfFIHtOA5ZvlxTm30jc1O1oZgq/lrFyHfn5LPsIMjeR8SEE1Cshn/w1KlJFtBJ+pxXxz39YUnxb7vXEbZp46NSfjsLgLF9YwfvipjLIoXS8ZHTad/IaSxRxm043ZaqTHpcEHxeUm4meKvXJeJ6W/WSasbA4aOGZ1Z25bAo4uYY0bkCZbka13qvvzKZ9vzbTdTdiKMeaxI1L/gX11KxtDAbdril4zTxDt7TPh71eL44jr1v+A8Oax/S/iQm4q8CuX4F2T3xE+n7RM4p01yknhfH85jjdOgqLVdpVqud82uluYnFEO6ZVKy5K6SCqe/bu3D6ViBNmxilhjJEyPlJphQrcUe3GK3qnWyrhUhQtZ3yEvnPvv9J/584o/4YJJx51Sv8VPDCR63UWzBhrXnPMPSycr/yeNobTwEFE1teRu+/3sLU1CNtA==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-superuser-auth
      namespace: rwx
      labels:
        cnpg.io/reload: ""
    type: kubernetes.io/basic-auth
