---
apiVersion: v1
kind: Service
metadata:
  name: dendrite
  labels:
    app.kubernetes.io/name: dendrite
    app.kubernetes.io/part-of: dendrite
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8008
    targetPort: http
  selector:
    app.kubernetes.io/name: dendrite
    app.kubernetes.io/part-of: dendrite
