---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mumble.fullname" . }}
  labels:
    {{- include "mumble.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: mumble
    protocol: TCP
    name: mumble
    nodePort: {{ .Values.service.port }}
  - port: {{ .Values.service.port }}
    targetPort: mumble-udp
    protocol: UDP
    name: mumble-udp
    nodePort: {{ .Values.service.port }}
  selector:
    {{- include "mumble.selectorLabels" . | nindent 4 }}
