apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: meta-rpc
  namespace: meta
spec:
  encryptedData:
    secret: AgARMOMcI5+Il3B1yyfn3ex1xs4ZBh+dXAkc8RbGmX+hDHO4XwRBg61Bsul3qAZG0ITMhjQkMbEDP4VSgs8K7EviB5Vs2/hZuQAIHjPN6XJfBofubOdYOeBYCPLVPsG4vAOhklV27LBP4WwpEb0hNaITMSK4gFa8+wrz7nGexv8k9eN8U86Q1EBbVkzQ7COI2DSw3kDSruARknEv8qqVd9bh78JlQtI99R2vJv9fuMKekxzvdsLMQiKOWVyCKroQgH6rOnnUDeidC/eu7JClVrgMdqwdsBRBOkPRHx3fgx4WYlXLuh4+c0a6FXJtGljRsV6W3KZXPPwjSf/bZipIAMLc45PFHtlTS40BPAV1rKmpZr8teyQaxgLnq7YYNQ19J2no0XoJtAQ39ux3UA0RNiWBHnztDBmq+aCCPYigCADRdzu6e7EM9a+nZXaKWBHPqxIC9COCTjf5E1rR3FruVzoZglEeXumN7xkalErn7mvWllCWC6550B1Ip8HmfyK3oCsP7U+dGuoOP7Yqr7lrIgHuf1izLQWrevYALFLPP9nTwseG9OlhvHJYcGpF6FgXVPeaA0qIzTethSWC3q4K0FleQkPFEtnEQtBCamWZCjYMHlChq4U9auiIeaFcyGV+NAaTkPRHPyQQtj79PCL/RxYG66jWW/vToNvk0dlv8ee8rGksHe3gX7R0l7q/7/q51Po16LS/AE9ZojJUGz7MTWq4H6Wi47bCHjnI+UBcJHFe0Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: meta-rpc
      namespace: meta
    type: Opaque

