apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uplink-nl-ams-scw-registry
  namespace: meta
spec:
  encryptedData:
    .dockerconfigjson: AgB9uUCR5XPA1JtC4yegrMxoNXMQRr+E2FYWY52c6sxmTRb26dFO2G6rBRRH7Nu+mPtbA9OIf7oubYs/qXckJttz7kbEANC5+tMJmK4N6aWinl7or2vMS6yPDuCT9i7oklxXEDSnAptTpG/3siuyx+b2lsouYZd8cVgTK0pxICwTCPlyJQuHztsWVBHublPHgDlaUG6sD4hWX9iIpF17H7kFZy66AOtc5Kspg2a2S4cpIPEOQy8Hnbu861EoI+TnQBq2syzeJE+FnV0zD9eRmOP4EdPWseMLlt/TFycUa65Hj5lhsPLEnGH3rtqO6efmJKPqqvwNrza/FhK3+92AYj7iyCgCQ1i8ObJX6hl8WWqWfuA7ToIs0Knnks7Mx+i0lBPxiMTJRsOozIgxi09+lgFP2sQTnJqKlnA0AfmbvS+CmxUqixNMBtMpwuopbNcwVY7Gl5PQfkIlc7NyLt1vVQ/2L14FaCgMLoDqh4t1sAeJHx7AIrlWIMYsx9ejSjJ07YR8R7KSkhW8UDBUDnF8KDcxINo2qjDvoBAj6OYrB0pCpPLVXMrZM08GqEgCUGp+lxoizstGVyQWtStd/N48vQSqs0H6XR/1RuRIvF3MYd7oV1WDCP4RmHYbEvOAPTsxd8KI8Qnb3AxruPAZ27A9yRMGumYa//9Rnn3ZznJjcehQ5tUicJuriAicceQ1Cq55FrqOqCNBTkYt4kkjKqKwPq75h6z2FNxToF7hO0PaG8jrQBDgPbvZaZU3iW0ixIcMgbQ8cpVukoML9BFZ0huA00VrhALCeHlInVUj+MvpggmHl6KiGbDDC8gas7TutfYZ4DYVBZf7LugE89m/sa6NIcKYXoMNUT7iZnkQ8jkvEO5gMwYH9eH/
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: uplink-nl-ams-scw-registry
      namespace: meta
    type: kubernetes.io/dockerconfigjson

