apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: meta-s3
  namespace: meta
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCtWx15kNEqTIIZ8MJar+MYq7tfLAAt4mJzfti3hIDxhFfcawUG3VcsN1uKf55z6OPU+lLWWHF9HhvrF9P+xYAGzaJlSM6AmQH33r/Fr0vi7v80IFhkaRghcXVzq07V/TmtUOSjJc6XvwZShfQi/r/8hzGkiSJyHgQXy4PDyWnpThWAc7u4CnOA3O1DERsjhi8evTYy1NSmW+wbt59at7+FYeJeAWDyvd0GOnBOAEk0vRCxtVc9mfA1TutqW1rRJa7GaQhxO6+4CF8/Dk4vkSIRSiZEOdL7R95s1XMiVFQAg+o7QBv6ItjTEgpUOOs78fC9MNVQlJ9UyK8buhX/f1sUWhWJ5e6fCHYhTJWnebGml0ZFZbAvRmyIZ/l60pIdwR/JFu+0JfqZcJ/vp+LLedhLz5LNlQ4z4eXiTrSIRzwmkfUL+S9u/OQKMLqTmdmwJx6iIyJuOMIYE8XezkYZQH3YY5HgYl0Q58u6AyGTAnB+DcJ+8Lt6s9l0/5OkmFEZlRufBUM4Vy6tIt1L0qOwKMA2jy0NfuQfjwkyZiqoM8V4j4OTxYQaU9mlpLR6UxbBTRd8LSMF5PJ1/dfbvYxmwh2rm3OXn0vqF+hoehXlrMXjvau5zXv3GpmB1pfSzLFK+IMG1mH/QZBVEK0RIGBlpdl5Vp3l+66WjS16ER4OCnc8owjJ7RVltWKhT320aNM+Dg9FYMI8q9/sI+q/bIS2eFNN/owPHw==
    AWS_SECRET_ACCESS_KEY: AgCEwzmhiFQFwmZlOwKkSBWmPSDxslVA45oY9pIvhotupSB7F053L4rKK0VmXUjFUNZyccG7hTvceESgD/ZoK0KOon46+EojWO1DIO59L88mMh7eXx19C9AedqngQuk33Ft6XBo2qyZjehWfJEittQOQqj+SkwN46UcA444QW+/GJtjWMn4MvMtqlT1ilUXMQnLpd9ZadtVDJtT/xBLOCleE0/sZLD7ai4z8vWDjLICzJf1dtuwsBTZYUvwbmM1iTO1kPpOvSWXiDowve0fpTQDeog7xjPfVGC7oHbEFHpx/xNlBuKyzaUFppExFrVQHx2mEl2/PyOxyGrbbmQy3jeCYjjlhQxkpR1EipTbDAO4yFYDc1b3n6Y1gYN0SN0f+HArBX7oOVzMroBZRKfosvhlWrg+XmLaodLe9zhO9p4axR7qxBWWUzuPvJD9FkrBEGcs/mqvTw0k6XBeTZ89Lw0MzQ+he577cwV2BmI+TeTK9bEYbOkvJVxK5FOi8Wl40nuLp2ABEi8vgxG4DlDCHo0KVbpLh1pvspqJUHEF3BT+wfPqQSPyO2htu6gUBivf567/c75CPoRAf1IarLM81rfERzmh7Cy+UNjitjooJhxlwwN1y2WffApCLolpjXa5lpzZjPY4ibAC7l3UJx9+XZFdtzhAIIY17d0LOBlEj63Ig6pIpenHABBaPA6HepUrcW3anKsz4aVdxzRH1FS3/JvjN1ukQu/iYlLbBoeQXKSX56OPrfzGDx6uH
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: meta-s3
      namespace: meta
    type: Opaque

