apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: redis
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rwx-redis-prod
    server: {{ .Values.spec.destination.server }}
  project: production
  source:
    path: redis
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
