apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: element-web
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: element-web
    server: {{ .Values.spec.destination.server }}
  project: production
  source:
    path: element-web
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
