apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-syncer
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubeops
    server: {{ .Values.spec.destination.server }}
  project: production
  source:
    chart: config-syncer
    repoURL: https://charts.appscode.com/stable/
    targetRevision: v0.14.1
