apiVersion: v1
kind: Namespace
metadata:
  name: chadgpt-anhero
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: chadgpt-anhero
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - {{ .Values.spec.source.repoURL }}
  destinations:
  - namespace: chadgpt-anhero
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chadgpt-anhero
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: chadgpt-anhero
    server: {{ .Values.spec.destination.server }}
  project: chadgpt-anhero
  source:
    path: chadgpt
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - values-anhero.yaml
  syncPolicy:
    automated: {}
