apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enshrouded-server
  namespace: argocd
spec:
  destination:
    namespace: enshrouded-server
    server: {{ .Values.spec.destination.server }}
  project: production
  source:
    path: enshrouded-server
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
