apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt2prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mqtt2prometheus
    server: {{ .Values.spec.destination.server }}
  project: production
  source:
    path: mqtt2prometheus
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
