apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: open-webui
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: open-webui
  sourceRepos:
  - {{ .Values.spec.source.repoURL }}
  destinations:
  - namespace: rwx-openwebui-prod
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rwx-openwebui-prod
    server: {{ .Values.spec.destination.server }}
  project: open-webui
  source:
    path: open-webui
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
