apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nats
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: NATS messaging system for data layer services
  sourceRepos:
  - {{ .Values.spec.source.repoURL }}
  destinations:
  - namespace: nats
    server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: nats
    server: {{ .Values.spec.destination.server }}
  project: nats
  source:
    path: nats
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
    - PrunePropagationPolicy=foreground
