apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: quickwit
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Search indexer
  sourceRepos:
  - {{ .Values.repository | quote }}
  destinations:
  - namespace: quickwit-prod
    server: https://kubernetes.default.svc

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickwit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: quickwit-prod
    server: {{ .Values.spec.destination.server }}
  project: quickwit
  source:
    path: quickwit
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - PruneLast=true
    - PrunePropagationPolicy=foreground
