apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redis
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: redis
  sourceRepos:
  - {{ .Values.spec.source.repoURL }}
  destinations:
  - namespace: redis
    server: https://kubernetes.default.svc
