apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitnami-sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bitnami-sealed-secrets
    server: {{ .Values.spec.destination.server }}
  project: production
  source:
    path: helm/bitnami-sealed-secrets
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
