---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infra-rwx-im
  namespace: rwx
spec:
  secretName: infra-rwx-im-tls
  secretTemplate:
    annotations:
      kubed.appscode.com/sync: 'im.rwx.infra/tls=true'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: '*.infra.rwx.im'
  dnsNames:
  - infra.rwx.im
  - '*.infra.rwx.im'
