---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infra-rwx-im
  namespace: rwx
spec:
  secretName: infra-rwx-im-tls
  secretTemplate:
    annotations:
      replicator.v1.mittwald.de/replicate-to: >
        argocd,grafana,longhorn-system,meta-oss,meta-webhook,meta,monitoring,rwx,traefik
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: '*.infra.rwx.im'
  dnsNames:
    - infra.rwx.im
    - '*.infra.rwx.im'
