apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubegres
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubegres-system
    server: {{ .Values.spec.destination.server }}
  project: production
  source:
    path: kustomize/kubegres
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
