apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn-system
    server: {{ .Values.spec.destination.server }}
  project: production
  source:
    path: helm/longhorn
    plugin:
      name: argocd-vault-plugin-helm
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
