apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mumble
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rwx
    server: {{ .Values.spec.destination.server }}
  project: production
  source:
    path: mumble
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
