---
apiVersion: v1
kind: Namespace
metadata:
  name: rwx
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: nats
---
apiVersion: v1
kind: Namespace
metadata:
  name: mosquitto
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    im.rwx.infra/tls: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: vector
---
apiVersion: v1
kind: Namespace
metadata:
  name: element-web
---
apiVersion: v1
kind: Namespace
metadata:
  name: mqtt2prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
  labels:
    im.rwx.infra/tls: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    im.rwx.infra/tls: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    im.rwx.infra/tls: 'true'
---
apiVersion: v1
kind: Namespace
metadata:
  name: magistr-prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeops
---
apiVersion: v1
kind: Namespace
metadata:
  name: enshrouded-server
