---
apiVersion: v1
kind: Namespace
metadata:
  name: rwx
---
apiVersion: v1
kind: Namespace
metadata:
  name: mosquitto
---
apiVersion: v1
kind: Namespace
metadata:
  name: nats
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: vector
---
apiVersion: v1
kind: Namespace
metadata:
  name: mqtt2prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: magistr-prod
