---
apiVersion: v1
kind: Namespace
metadata:
  name: meta
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-events
  labels:
    im.rwx.infra/tls: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: rwx
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: influxdb
  labels:
    im.rwx.infra/tls: true
