traefik:
  instanceLabelOverride: traefik

  image:
    # renovate: datasource=docker depName=traefik
    repository: traefik
    tag: v3.7.6
    digest: "sha256:d6858791f9e74df44ca4014166647c41cdc2abd3bf2a71b832ca4e1c6a91b257"

  deployment:
    # Deploy multiple replicas.
    replicas: 3

  global:
    # Disable sending of anonymous usage statistics.
    sendAnonymousUsage: false
    # Don't check for new versions.
    checkNewVersion: false

  log:
    format: json
    level: DEBUG

  accessLog:
    enabled: false
    format: json

  metrics:
    # Enable prometheus metrics
    prometheus:
      service:
        enabled: true
      disableAPICheck: true # Disable API check of e.g. ServiceMonitor CRDs.
      serviceMonitor:
        enabled: true
        additionalLabels:
          metrics.uplink.io/monitor: prometheus
        jobLabel: app.kubernetes.io/instance
        prometheusRule:
          enabled: true
          rules:
            - alert: TraefikDown
              expr: up{job="traefik"} == 0
              for: 5m
              labels:
                context: traefik
                severity: warning
              annotations:
                summary: "Traefik Down"
                description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"

  # Configuration providers.
  providers:
    # Enable Kubernetes CRD provider.
    kubernetesCRD:
      enabled: true
      # Allow IngressRoutes to reference resources in other namespaces
      allowCrossNamespace: true

  service:
    annotations:
      lbipam.cilium.io/ips: 10.0.3.1
      lbipam.cilium.io/sharing-key: traefik
    spec:
      # Use a local traffic policy so we can get the users origin ip
      externalTrafficPolicy: Local
