# Default values for mumble.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: mumblevoip/mumble-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "@sha256:9ddc5f9f8c396c9f2ca3af22330609fee9c5607b2275539758f19e707f1ce6e4"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10000
  allowPrivilegeEscalation: false

service:
  type: LoadBalancer
  loadBalancerIP: "10.0.3.2"
  port: 31738

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

murmur:
  # The name of the server.
  serverName: rwx.im

  # Maximum number of concurrent clients allowed.
  users: 1000

  # Maximum bandwidth (in bits per second) clients are allowed to send speech
  # at.
  bandwidth: 256000

  tls:
    # The name of the secret that contains a tls certificate and key.
    secretName: rwx-im-tls
