# Default values for mumble.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mumblevoip/mumble-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 10000
  allowPrivilegeEscalation: false

service:
  type: LoadBalancer
  # The LoadBalancer IP to use. If not set, the cloud provider will assign one.
  loadBalancerIP: "10.0.3.2"
  port: 31738

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}

tolerations: []

networkPolicy:
  enabled: false

affinity: {}

podDisruptionBudget:
  enabled: false
  minAvailable: 1
  maxUnavailable: 1

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 500Mi

murmur:
  # The name of the server.
  serverName: rwx.im

  # Maximum number of concurrent clients allowed.
  users: 1000

  # Maximum number of concurrent users per channel.
  usersPerChannel: 0

  # Maximum bandwidth (in bits per second) clients are allowed to send speech at.
  bandwidth: 256000

  # Password to join server. Leave empty to make the server public.
  serverPassword: ""

  # Welcome message sent to clients when they connect.
  welcomeText: "<br />Welcome to this server running <b>Murmur</b>.<br />Enjoy
    your stay!<br />"

  tls:
    # The name of the secret that contains a tls certificate and key.
    secretName: rwx-im-tls

# Liveness probe configuration
livenessProbe:
  tcpSocket:
    port: mumble
  initialDelaySeconds: 30
  periodSeconds: 10

# Readiness probe configuration
readinessProbe:
  tcpSocket:
    port: mumble
  initialDelaySeconds: 15
  periodSeconds: 10
