{{- with .Values.persistence }}
{{- if .enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "open-webui.fullname" $ }}
  labels:
    {{- include "open-webui.labels" $ | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .storageClass | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- end }}
{{- end }}
