grafana:
  image:
    tag: 12.0.1
  # -- Set the number of replicas to deploy.
  replicas: 2

  # -- Configure the Grafana instance.
  grafana.ini:
    server:
      domain: grafana.infra.rwx.im
      root_url: https://%(domain)s

    users:
      auto_assign_org_id: 2

  persistence:
    enabled: false

  envFromSecret: grafana-env

  sidecar:
    # -- Enable sidecar that monitors for dashboards from ConfigMaps
    dashboards:
      enabled: true
      # -- The label to watch for
      label: 'grafana.com/dashboard'
      # -- The value to match
      labelValue: 'true'
      # -- Only monitor ConfigMaps
      resource: configmap

  admin:
    existingSecret: grafana-auth

  imageRenderer:
    enabled: true
    # image:
    #   tag: '3.8.4'

ingress:
  enabled: true
  hostname: grafana.infra.rwx.im
  tls:
    secretName: infra-rwx-im-tls
