grafana:
  admin:
    existingSecret: grafana-auth

  envFromSecret: grafana-env

  image:
    # renovate: datasource=docker depName=grafana/grafana
    repository: grafana/grafana
    tag: 13.2.1
    sha: ""

  imageRenderer:
    enabled: true

    image:
      # renovate: datasource=docker depName=grafana/grafana-image-renderer
      repository: grafana/grafana-image-renderer
      tag: v5.12.3
      sha: "sha256:cf36a94431662540a72d2058a43e0cbf72638334475d8216a25a77526a627be7"

    # Configure deployment of ServiceMonitor for the image renderer.
    serviceMonitor:
      # Enable service monitor for image renderer.
      enabled: true
      labels:
        metrics.uplink.io/monitor: prometheus

  grafana.ini:
    server:
      domain: grafana.infra.rwx.im
      root_url: https://%(domain)s

    users:
      auto_assign_org_id: 2

  persistence:
    enabled: false

  plugins:
    - quickwit-quickwit-datasource

  # -- Set the number of replicas to deploy.
  replicas: 2

  # Configure deployment of ServiceMonitor.
  serviceMonitor:
    # Enable deployment of ServiceMonitor.
    enabled: true
    labels:
      metrics.uplink.io/monitor: prometheus

  sidecar:
    # -- Enable sidecar that monitors for dashboards from ConfigMaps
    dashboards:
      enabled: true
      # -- The label to watch for
      label: "grafana.com/dashboard"
      # -- The value to match
      labelValue: "true"
      # -- Only monitor ConfigMaps
      resource: configmap

certificate:
  # -- Create the Certificate resource.
  enabled: true
  # -- Override the name of the certificate
  name: grafana.infra.rwx.im
  # -- The domain name
  commonName: grafana.infra.rwx.im
  # -- Reference to the certificate issuer
  issuer:
    kind: ClusterIssuer
    name: letsencrypt-production
  # -- Override the name of the secret that cert-manager will use.
  secretName: ""

ingressRoute:
  enabled: true
  hostname: grafana.infra.rwx.im
  tls:
    secretName: grafana.infra.rwx.im-tls
