grafana:
  image:
    # renovate: datasource=docker depName=grafana/grafana
    repository: grafana/grafana
    tag: 13.0.2
    sha: ""

  # -- Set the number of replicas to deploy.
  replicas: 2

  imageRenderer:
    image:
      # renovate: datasource=docker depName=grafana/grafana-image-renderer
      repository: grafana/grafana-image-renderer
      tag: 5.8.9
      sha: ""

  plugins:
    - quickwit-quickwit-datasource
    # -- Configure the Grafana instance.

  grafana.ini:
    server:
      domain: grafana.infra.rwx.im
      root_url: https://%(domain)s

    users:
      auto_assign_org_id: 2

  persistence:
    enabled: false

  envFromSecret: grafana-env

  sidecar:
    # -- Enable sidecar that monitors for dashboards from ConfigMaps
    dashboards:
      enabled: true
      # -- The label to watch for
      label: "grafana.com/dashboard"
      # -- The value to match
      labelValue: "true"
      # -- Only monitor ConfigMaps
      resource: configmap

  admin:
    existingSecret: grafana-auth

ingressRoute:
  enabled: true
  hostname: grafana.infra.rwx.im
  tls:
    secretName: grafana.infra.rwx.im-tls

certificate:
  # -- Create the Certificate resource.
  enabled: true
  # -- Override the name of the certificate
  name: grafana.infra.rwx.im
  # -- The domain name
  commonName: grafana.infra.rwx.im
  # -- Reference to the certificate issuer
  issuer:
    kind: ClusterIssuer
    name: letsencrypt-production
  # -- Override the name of the secret that cert-manager will use.
  secretName: ""
