{{- range $key, $value := .Values.applications -}}
{{- $path := default $key .path }}
{{- $disableAutoSync := default false .disableAutoSync }}
{{- $namespace := default $key .namespace | quote }}
{{- $selfHeal := default true .selfHeal }}
{{- $finalizer := default true .finalizer }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: {{ include "apps-of-apps.argocdNamespace" $ }}
{{- if $finalizer }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
{{- end }}
spec:
  destination:
    namespace: {{ $namespace }}
    server: {{ $.Values.destination.server }}
  project: {{ $.Release.Name }}
  source:
    path: {{ default $key .path }}
    repoURL: {{ $.Values.repository }}
{{- with .source }}
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- if not $disableAutoSync }}
  syncPolicy:
    automated:
      {{- if (ne false .automatedPrune) }}
      prune: true
      {{- else }}
      prune: false
      {{- end }}
      selfHeal: {{ $selfHeal }}
    syncOptions:
    - ApplyOutOfSyncOnly=true
{{- end }}
{{- end }}
