apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-compact
  labels:
    app.kubernetes.io/name: thanos-compact
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos-compact
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos-compact
    spec:
      containers:
      - name: thanos-compact
        image: quay.io/thanos/thanos:v0.37.2
        args:
        - compact
        - --log.level=debug
        - --data-dir
        - /data
        - --objstore.config=$(OBJSTORE_CONFIG)
        env:
        - name: OBJSTORE_CONFIG
          valueFrom:
            secretKeyRef:
              key: thanos.yaml
              name: thanos-storage
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: thanos-data-dir
          mountPath: /data
      volumes:
      - name: thanos-data-dir
        emptyDir: {}
