images:
  - name: quay.io/thanos/thanos
    newTag: v0.42.4@sha256:b567818fe608067eb0f1d7c2c4fe361e7ad83c8a256234c97685f1d0bf670cc8
resources:
- ./manifests/sealedsecret.thanos-storage.yaml
- ./manifests/deployment.thanos-query.yaml
- ./manifests/statefulset.thanos-compact.yaml
- ./manifests/statefulset.thanos-store.yaml
- ./manifests/service.thanos-query.yaml
- ./manifests/service.thanos-sidecar.yaml
- ./manifests/service.thanos-store.yaml
- ./manifests/servicemonitor.thanos-store.yaml
