images:
  - name: quay.io/thanos/thanos
    newTag: v0.42.2@sha256:6249f7aaadd3695df637fb2eb4cb9a9955611eee691c3970892fe9c0dc3f2db6
resources:
- ./manifests/sealedsecret.thanos-storage.yaml
- ./manifests/deployment.thanos-query.yaml
- ./manifests/statefulset.thanos-compact.yaml
- ./manifests/statefulset.thanos-store.yaml
- ./manifests/service.thanos-query.yaml
- ./manifests/service.thanos-sidecar.yaml
- ./manifests/service.thanos-store.yaml
- ./manifests/servicemonitor.thanos-store.yaml
