apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar
  labels:
    app.kubernetes.io/name: thanos-sidecar
spec:
  clusterIP: None
  ports:
  - name: http
    port: 10902
    targetPort: http
  - name: grpc
    port: 10901
    targetPort: grpc
  selector:
    metrics.uplink.io/monitor: prometheus
