apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-backup-aws-creds
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgCp9zUUVj/7XGRyx9oI0JPpmA/IQMgjMabVbvrR5zpCfcriH86GQ4pQlFg2zLNO0dtzKfC+pVyRonT/VmiSov3J/lQfcI0drDzvx/N2wjWFTK1h9Xr2QBHMhSfoBUIt9wrTp4Kke9NGqlHrV4+YzhT2DJb+t51tUMzCjiFHze67jG+eh3t/vnD2lOvFetKWzwuyKZDAqwH2+I8fGk/xjXNwGD11i6LoFPHCGkLw05HDxHh4jB7DejH+oGGLP2VDvuECT98nDukEzXTNyGabnhSIb7apyXb0zbx2Co9twEpSFYkYAsfMKejE5Arz/MgMwYNRYA1uM1d1T4Z/cFAnPUE2xtT/0DVGL4NbPGXvmm9pDXqmrMg7FWuAL51Qrn600wGYzyEgq8zXgGp7WPZP4ZLebWRR4iJaMJyFlt/cCtJTZixqkRY4TlF6A2rYYm5m8GPzBkML+lSAPLWXjZSf/WFpEOb2rPSWVM/SRcNiA3TQhK7ZY9RSkAxQQgeXiacDzgDJ64bgIlS8bWwpOlrKnyYpVtQASUTZ9O0VHqvWe8NVeiQv8wvp1TKZjcwZaJ15t8dUuflkYRUymQAlN23PSFxnxsepA+ZTLKEKXBP6Y7phvKjiDeLZuHch/pk5yyPRnmzybZjBfKc2h0+QMP4GCfONCEuGXb43bsYArEiTrqSXF21xNAgEO8bLn8sFYImP64SartMv7fC8YwcLSN161IG+mD9g+A==
    AWS_SECRET_ACCESS_KEY: AgCYCAYG+cOfUWXguyRNGPzEMSX4f/8lctA+cEY96W00MDwOoC+px/odIV/jrdfMB+5yZ0HAt2YzjkI1Ze8tXp1hHItQDp1/WHuozXCKtTiH9QXfnSHaVLTqpKN/4iW7hyQ3tRRpCl1XmFxQN1V06fmsstRR5Gjkatr+vM0/+2Z9U5f6SCm/0JcI0zOU715McvrUl9hLuBFj9Ev7bSydUm/YYWa6Qtx8nP7Zf0mvG6aTeKblrs57eUJDOgZNU6Z4ngEciHwmV8MhWviD6M//H9x/grKK6szk6uhLqFfMoRsi6oOyf88deO9O0LkpRZvbC7howih1qRgAzzEiHn15xyneRuGbqUnIawdyLFskT/ypQP05o9zhZ566N+DDoeNTs2NefkuiXSWilZUZcNnAp19+xQPP5de7vPltCpxb1VXNbtxqut83vt8+JvQ8uIVFQa/UQag9uGDLIBigFxlpfhP+iE3KG9n42kgLSr/xtBWWGsg0Ltmu+9c4ES68gCj488A0BbgDr3/imrIUJbeyHjE4+LU7R7Ofo4BugI0ZFzuu5Y6qzMaBFWsvyFFeXEdZbKe2w113NX0UPKlDYKX50WSRPG635FTs/SMX8ma9nEOiO9z/U+4n3j8unCC+UwKj5/wD98lowGxxeRVHKNUQD0otKQah98ShwGFybt3VMr/qrgKPMxOakqMgMJzQeYFyynclvubiaX7fse39S4qY0jlPskv5NwilF5Ro6OAufQ0aqn3p7oEeCEVc
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: longhorn-backup-aws-creds
      namespace: longhorn-system
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-http-auth
  namespace: longhorn-system
spec:
  encryptedData:
    users: AgAMgjCmvNJJd8M3jeVbyF3M0x5EUYJy1tbDCYzTV5gr62Om3Ji5yUzVKr2wrRSoKYBA7rEHrch2NhK3DJtzKImPhDeOCcdNo2sWUagFU+B1QdL6NffnftvvcR19iwRL2o9ngYIzAYd3ModcjiGVNMnnN0+2zFfaciP306Klj+Zl9DNfQ+NEGHZjRyPEHvAIXeGfjP9MkfMiWqA+r/EcE5ylpVSNkIdPRwAjkoLIyB6YybHAyyj9El0xRl8xlBPsBlQfu/ax3jYRgEq1XbLdA76s2hLTM8EFy5FFtqu1bX0s38s+0YFEKHbwu9r9nggJrKs7B2iFO0S/M66HNH3f0wu/f6CzhZoPfmaifhhd57nIdyRpm2wKJzUNQr0X4Gzx5VDvKaeKtChGExqLlhLRUc+DPJK7AzMOzzAWTzPYBHUGyGsdGMI4gYIz2TKkCGCnfOUeocyNsHXlwEQZC42Ab11lKBMOGJ/Bvfj8tPuF0BUviZzsNA9d2tkroNTOqAGR6qStCjYdxsh39ncGrE077z2WNRGE7UOfP1KUE5asfRmu3xaYSXxmF430Fz5JPE6l6qFTT++I7CE3BvsK8TwH+LGDp0WqTEawRAFrbbYytZ07w6bliy2fLfUkqcrvh9GFV8JGMyGconK2jLelhTtx/jRLwkNQ1b1DmGm/G9DbaDjpWb972hILUe3fQLYj4YUA1sAhcS6Z3BUhHlbfN5z4M59X0joSmtCSwE8O+C6OE8cQU3W9n9HPhcc/JyedtqIHr+BO5hGc19NDSydtheEE6Jg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: longhorn-http-auth
      namespace: longhorn-system
