apiVersion: v1
kind: Secret
metadata:
  name: backblaze-b2
  namespace: longhorn-system
  annotations:
    vault.security.banzaicloud.io/vault-role: meta
    vault.security.banzaicloud.io/vault-serviceaccount: default
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
stringData:
  AWS_ACCESS_KEY_ID: 'vault:secret/longhorn/backblaze-b2#AWS_ACCESS_KEY_ID'
  AWS_ENDPOINTS: 'vault:secret/longhorn/backblaze-b2#AWS_ENDPOINTS'
  AWS_SECRET_ACCESS_KEY: 'vault:secret/longhorn/backblaze-b2#AWS_SECRET_ACCESS_KEY'
