---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: '2'
  staleReplicaTimeout: '2880' # 48 hours in minutes
  fromBackup: ""
  diskSelector: ssd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: '2'
  staleReplicaTimeout: '2880' # 48 hours in minutes
  fromBackup: ""
  diskSelector: hdd
