apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt2prometheus.fullname" . }}
  labels:
    {{- include "mqtt2prometheus.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}
