apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt2prometheus.fullname" . }}
  labels:
    {{- include "mqtt2prometheus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mqtt2prometheus.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include "mqtt2prometheus.configmapChecksum" . }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mqtt2prometheus.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["-config", "/config/config.yaml"]
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        env:
        - name: MQTT2PROM_MQTT_USER
          valueFrom:
            secretKeyRef:
              key: mqtt-username
              name: {{ .Values.secretName | quote }}
        - name: MQTT2PROM_MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mqtt-password
              name: {{ .Values.secretName | quote }}
        livenessProbe:
          httpGet:
            path: /metrics
            port: http
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: {{ include "mqtt2prometheus.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
