---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt2prometheus-auth
  namespace: mqtt2prometheus
spec:
  encryptedData:
    mqtt-password: AgCUjZQIH/HUTwW7QiKCGnbwF8kJB2Kou13MnF4OUKo/eFgZ5kxCsqLd+LUJ6+tAn+a7LQwzNxhBCKzJsihbLfdnwvpkLN7fKFEgk73kqcg7Fuy5BOocKfzuYCPB+Q5OxBhiAhPfuh9oUyZ8n1G6QAKLwi3oGxMDrOHlMwmBtBODBLBDycv+AFkr23GUZdMfFec95462RJ9ZEr8JmnYiPvJoSsrEhZP6vgjWawTJoDdxjQZJKGzD8ee8nQ/7COGoNfpeDAnaK4vsqrPUHlEsVX19c92SzxUNSulrNzUzDJtvl3Mb1AUSzVzMOF/+q+oOMXfO3/RV5kNYraaPRQEiL5HyqGiLAzCoC+zmt5V6pc7Ou7nFZaybwJy2Tj+ZBQhCZgAcacxh1UWb/Hqov+AXj/Js+00sMt4rYnALg4LeIYKjoNkiFus2znHh7jDyvXCcVwNkKQZLyOCSiRT7lqgigR1S0i1gsWsJT3H0WboGNiPKR7pYAQMcDGS2iPUGMF52aC9h9lDkZs68mhwdiPplkb4MVwmfHxRV43/lpgklagxfv1SooAHQxZQm9VhLm5QV+scr+sbuFmfqZ2o7XmmTIvDcLd4+m/sp4P5SBCtMM4JxqzB0jqCzFalvikGamf+4Jm22MhtY7zIFLUAB76S3gTgpzQUZQ7heDoGcbY7ugqthYQ4cN2nAM53KvgsDXiTRHeLBLrUm4SSnjk3v33FD05uFf7u0o4sl1rMtviqNgE3zLw==
    mqtt-username: AgBn3g6KThnEjdGGrjiiWAadSessbOtHdT4VCOhICNlkE9LQDZpKclw34Rr3HOohRejqiaV2uyciPof+jNz2ZJwjdyLcp2E2MWoWfOFtxY5yd0Z+27/i2XJD6zWUxgc8MO6Qtpzwxj/CrH/0Gz7XmtiAUZzwVEUjyfZ8lGw6XwF2MkNncQ9K3NVCgxqOrFhfg92pO4droABV9ErKwTW2pXvBhhmvmWCS0IkUFSYTwzF0fT3++PrbLWDoO7Zxp2fhdLQgqeQKtSpA2HsPLvMAnhPNbwmLX0LvAVBP+3gX82txyKx9k8YipP5viIG9O+EIWfq3J6vtfFQlt+8Og6gbgYOKSXxfrIOquxab6YYG+j3RlA96ucm7WSqdeSmYEcOwmIvOMSKGc2f4jzHQPiTHVR5KHElKC7+wqQXYmy25WFlQS3OL32rlUJvuHNaiVY6hIpvjDzsKdRl8LUvcUv2GoKlG0C/Yv5EQQyflLLTft8twHJVSvEAnOfXbPTFNCdqh0gTBQhtNmmsULnb1fNTc5WSnQQXGS/Qw+3K/CYFjODLteACWhEbwi+6aY5LO81Z3iK2sjg5J3ifS8MvnMgByWa6AdjdqmQHfUrBXwx3OFZOu4xz8ig3oOeBMi/2i7xpdbTJ8EtLELafd2C4fh2ooNTo93DC2FDVwSC/AURwCyKshH8w4EVQohbuUF+0DGGlqsiBEn01KCWSL7AXivvixlEE=
  template:
    metadata:
      creationTimestamp: null
      name: mqtt2prometheus-auth
      namespace: mqtt2prometheus
    type: Opaque
