apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Production
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Allow deployments in all namespaces on our local cluster
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  # Whitelist all API resources
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
