bases:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.2.0
resources:
- ingressroute.yaml
patchesJson6902:
- path: overlays/production/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1
