influxdb2:
  adminUser:
    existingSecret: influxdb-auth

  persistence:
    enabled: true
    storageClass: ssd
    accessMode: ReadWriteOnce
    size: 100Gi

  ingress:
    enabled: true

    # Enable TLS termination
    tls: true
    secretName: rwx-im-tls
    hostname: influxdb.infra.rwx.im
    path: /
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"

