apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        runAsNonRoot: true
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        resources:
{{ toYaml .Values.resources | indent 10 }}
        envFrom:
        - secretRef:
            name: enshrouded-env
            optional: false
        env:
        - name: SERVER_NAME
          value: {{ .Values.env.serverName | squote }}
        - name: GAME_PORT
          value: {{ .Values.env.gamePort | squote }}
        - name: QUERY_PORT
          value: {{ .Values.env.queryPort | squote }}
        - name: SERVER_SLOTS
          value: {{ .Values.env.serverSlots | squote }}
        ports:
        - name: game-port
          containerPort: {{ .Values.env.gamePort | int }}
          protocol: UDP
        - name: query-port
          containerPort: {{ .Values.env.queryPort | int }}
          protocol: UDP
        volumeMounts:
        - name: data
          mountPath: /home/steam/enshrouded/savegame
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "{{ .Chart.Name }}-data"
