resources:
  - ./manifests/clusterrole.yaml
  - ./manifests/clusterrolebinding.yaml
  - ./manifests/serviceaccount.yaml
  - ./manifests/prometheus.yaml
  - ./manifests/service.yaml
  - ./manifests/servicemonitor.yaml
