apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 10.0.3.3
  ports:
  - protocol: TCP
    port: 1883
    targetPort: 1883
