{{- if and (not .Values.renovate.existingConfigMap) .Values.renovate.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "renovate.fullname" . | quote }}
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
data:
  config.json: |
    {{- toPrettyJson .Values.renovate.config | nindent 4 }}
{{- end }}
