{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "renovate.fullname" . }}-cache
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
spec:
  {{- with .Values.persistence.accessModes }}
  accessModes:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "1Gi" | quote -}}

  {{ with .Values.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
