vector:
  replicas: 1
  role: "Aggregator"

  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      internal_metrics:
        type: internal_metrics
      vector:
        address: 0.0.0.0:6000
        type: vector
        version: "2"
    sinks:
      prom_exporter:
        type: prometheus_exporter
        inputs: [internal_metrics]
        address: 0.0.0.0:9090
      loki:
        type: loki
        inputs: [vector]
        endpoint: "http://loki-gateway.loki.svc:80"
        encoding:
          codec: json
      stdout:
        type: console
        inputs: [vector]
        encoding:
          codec: json
