vector:
  role: "Agent"

  resources:
    requests:
      memory: "64Mi"
      cpu: "500m"
    limits:
      memory: "1024Mi"
      cpu: "6000m"

  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      generate_syslog:
        type: demo_logs
        format: syslog
      kubernetes_logs:
        type: kubernetes_logs
        node_annotation_fields:
          node_labels: "" # Disable node labels as kubevirt adds a whole lot and we don't care about them
      host_metrics:
        filesystem:
          devices:
            excludes: [binfmt_misc]
          filesystems:
            excludes: [binfmt_misc]
          mountPoints:
            excludes: ["*/proc/sys/fs/binfmt_misc"]
        type: host_metrics
      internal_metrics:
        type: internal_metrics
    sinks:
      prom_exporter:
        type: prometheus_exporter
        inputs: [host_metrics, internal_metrics]
        address: 0.0.0.0:9090
      aggregator:
        type: vector
        inputs: [host_metrics, internal_metrics, kubernetes_logs]
        address: "vector-aggregator.vector.svc.cluster.local:6000"
