vector:
  replicas: 1
  role: "Aggregator"

  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      internal_metrics:
        type: internal_metrics
      vector:
        address: 0.0.0.0:6000
        type: vector
        version: "2"
    transforms:
      vector_logs:
        type: filter
        inputs: [vector]
        condition:
          type: is_log
    sinks:
      prom_exporter:
        type: prometheus_exporter
        inputs: [internal_metrics]
        address: 0.0.0.0:9090
      quickwit:
        type: http
        method: post
        inputs: [vector_logs]
        encoding:
          codec: json
        framing:
          method: newline_delimited
        uri: "http://quickwit-control-plane.quickwit-prod.svc.cluster.local:7280/api/v1/otel-logs-v0_7/ingest"
