---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-http-auth
  namespace: longhorn-system
spec:
  encryptedData:
    users: AgCc712BxbCNhMyoZ0+eQQeQ6FD9HbkLQiiApJHdp4DlwkTGueLMkS4QQ7hzffQMhHZZWBl+8NswHr/hT7GRVK+hFOD4pN3mJY/bmB+YNA1j2+hj7fnt1rMMyc4zJ4Zb7OA5nj3Z69s/O76NFMP37pGSC9ZpUQ7nlDrbBuiqZlG2f2mtkJTe0nIHltA55iY01fWPKISiHK18pdfUcwQrkYkqdHMrF8vcZSSN5ETQPKHyjqKLoMZELu2CvBUC7Tilfnzq8zDtopqn58lBNBIAXY4ovnlGRKyk/tu8cwfWHB2GIm2MWMsfOlgHq1k3MdHLuAQc15NDbuvh3CdbD3WXk2IjD2ImZet9nfRmqg97QJ3xOuWgZTYaFgDT/U72yFo7eooBxsWSbHEAwO5qP3eyUbST9XMMXZ7jlCCrUSzmg5uqGnejXUQ7is30o26S0h/fZ8+tMtK8pdNbLwPAJgMGVcfASziNi4alPh7xILs5oJXLBVIz7Ddl6FkI9qjNsIZ8QINfEsSEEZlLyxEPbnaGU5SoqDOjnilh1gPATT5BWZmeUWGHHKxrxNhEMTLbLOk6e7q8ObOQt6Errj89j8H3sZj2SBPSUY2v5YOtZY/Try1FCGnOAUreVYRWZonEIXvzXoWPE1EGmYsIDN5DorLqCFIGPXP/tHat9aenlAVfn93kxaV+jHiMkSegmxAzpYDSMJ8zj6HnqjTHPtiMuMVaaJ5qYsHMD7vSl1VoBFXWR4pRgAoW6TaiuirObtYnXTXNONM7/pap7psoRvsPG8tXF7U=
  template:
    metadata:
      creationTimestamp: null
      name: longhorn-http-auth
      namespace: longhorn-system
