---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: '2'
  staleReplicaTimeout: '2880' # 48 hours in minutes
  fromBackup: ""
  diskSelector: ssd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: '2'
  staleReplicaTimeout: '2880' # 48 hours in minutes
  fromBackup: ""
  diskSelector: hdd
---
{{- range $class := (tuple "hdd" "ssd") }}
{{- range $replicas := untilStep 1 4 1 }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $class }}-gp1x{{ $replicas }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: {{ $replicas | quote }}
  diskSelector: {{ $class | quote }}
---
{{- end }}
{{- end }}
