{{- range $key, $value := .Values.applications -}}
{{- $automatedPrune := default true .automatedPrune -}}
{{- $disableAutoSync := default false .disableAutoSync -}}
{{- $selfHeal := default true .selfHeal }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $key }}
  namespace: {{ include "app-of-apps.argocdNamespace" $ }}
spec:
  destination:
    namespace: {{ $.Values.destination.namespace }}
    server: {{ $.Values.destination.server }}
  project: {{ $.Release.Name }}
  source:
    path: {{ default $key .path }}
    repoURL: {{ $.Values.repository }}
{{- with .source }}
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- if not $disableAutoSync }}
  syncPolicy:
    automated:
      prune: {{ $automatedPrune }}
      selfHeal: {{ $selfHeal }}
    syncOptions:
    - ApplyOutOfSyncOnly=true
{{- end }}
{{- end }}
