repository: https://github.com/mkroman/k8s.git

argocdNamespace: argocd

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mkroman/k8s
    targetRevision: HEAD

applications:
  - name: k8s-meta-apps
  - name: k8s-rwx-apps

# -- List of Argo CD projects.
projects:
  - name: zeta
    destinations:
      - namespace: zeta-prod
      - namespace: zeta-dev
    sourceRepos:
      - https://github.com/mkroman/k8s

  - name: chadgpt
    destinations:
      - namespace: chadgpt
    sourceRepos:
      - https://github.com/mkroman/k8s

  - name: chadgpt-magistr
    destinations:
      - namespace: chadgpt-magistr
    sourceRepos:
      - https://github.com/mkroman/k8s

# List of namespaces to create.
namespaces:
  - name: cert-manager
  - name: chadgpt
  - name: chadgpt-magistr
  - name: zeta-prod
  - name: zeta-dev

newApplications:
  - name: cert-manager
    project: cert-manager
    source:
      repoURL: https://github.com/mkroman/k8s
      path: cert-manager

  - name: chadgpt
    project: chadgpt
    source:
      repoURL: https://github.com/mkroman/k8s
      path: chadgpt

  - name: chadgpt-magistr
    project: chadgpt-magistr
    source:
      repoURL: https://github.com/mkroman/k8s
      path: chadgpt
      helm:
        valueFiles:
          - values-magistr.yaml

  - name: zeta
    annotations:
      argocd.argoproj.io/sync-wave: "2"
    project: zeta
    destination:
      namespace: zeta-prod
    source:
      repoURL: https://github.com/mkroman/k8s
      path: zeta
      helm:
        valueFiles:
          - values-prod.yaml
