repository: https://github.com/mkroman/k8s.git

argocdNamespace: argocd

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/mkroman/k8s
    targetRevision: HEAD

applications:
  - name: k8s-meta-apps
  - name: k8s-rwx-apps

# -- List of Argo CD projects.
projects:
  - name: cert-manager
    destinations:
      - namespace: cert-manager
      - namespace: kube-system
    sourceRepos:
      - https://github.com/mkroman/k8s
    clusterResourceWhitelist:
      - kind: ClusterRole
        group: rbac.authorization.k8s.io
      - kind: ClusterRoleBinding
        group: rbac.authorization.k8s.io
      - kind: MutatingWebhookConfiguration
        group: admissionregistration.k8s.io
      - kind: ValidatingWebhookConfiguration
        group: admissionregistration.k8s.io
      - kind: CustomResourceDefinition
        group: apiextensions.k8s.io
      - kind: ClusterIssuer
        group: cert-manager.io

  - name: chadgpt
    destinations:
      - namespace: chadgpt
    sourceRepos:
      - https://github.com/mkroman/k8s

  - name: chadgpt-magistr
    destinations:
      - namespace: chadgpt-magistr
    sourceRepos:
      - https://github.com/mkroman/k8s

  - name: cloudnative-pg
    destinations:
      - namespace: cnpg-system
    sourceRepos:
      - https://github.com/mkroman/k8s
    clusterResourceWhitelist:
      - kind: ClusterRole
        group: rbac.authorization.k8s.io
      - kind: ClusterRoleBinding
        group: rbac.authorization.k8s.io
      - kind: MutatingWebhookConfiguration
        group: admissionregistration.k8s.io
      - kind: ValidatingWebhookConfiguration
        group: admissionregistration.k8s.io
      - kind: CustomResourceDefinition
        group: apiextensions.k8s.io
      - kind: ''
        group: Namespace
        name: cnpg-system

  - name: open-webui
    destinations:
      - namespace: rwx-openwebui-prod
    sourceRepos:
      - https://github.com/mkroman/k8s

  - name: zeta
    destinations:
      - namespace: zeta-prod
      - namespace: zeta-dev
    sourceRepos:
      - https://github.com/mkroman/k8s

# List of namespaces to create.
namespaces:
  - name: cert-manager
  - name: chadgpt
  - name: chadgpt-magistr
  - name: rwx-openwebui-prod
  - name: zeta-prod
  - name: zeta-dev

newApplications:
  - name: cert-manager
    project: cert-manager
    source:
      repoURL: https://github.com/mkroman/k8s
      path: cert-manager

  - name: chadgpt
    project: chadgpt
    source:
      repoURL: https://github.com/mkroman/k8s
      path: chadgpt

  - name: chadgpt-magistr
    project: chadgpt-magistr
    source:
      repoURL: https://github.com/mkroman/k8s
      path: chadgpt
      helm:
        valueFiles:
          - values-magistr.yaml

  - name: cloudnative-pg
    project: cloudnative-pg
    destination:
      namespace: cnpg-system
    source:
      repoURL: https://github.com/mkroman/k8s
      path: cloudnative-pg
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - ApplyOutOfSyncOnly=true
        # We need to use server-side apply because the CRD metadata is too large.
        - ServerSideApply=true

  - name: open-webui
    project: open-webui
    destination:
      namespace: rwx-openwebui-prod
    source:
      repoURL: https://github.com/mkroman/k8s
      path: open-webui

  - name: zeta
    annotations:
      argocd.argoproj.io/sync-wave: "2"
    project: zeta
    destination:
      namespace: zeta-prod
    source:
      repoURL: https://github.com/mkroman/k8s
      path: zeta
      helm:
        valueFiles:
          - values-prod.yaml
