---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: deployment
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  webhook:
    deploy:
      endpoint: /deploy
      method: POST
      port: '12000'
      url: 'https://events.infra.rwx.im'
      authSecret:
        name: webhook-access
        key: token
