image: sknnr/enshrouded-dedicated-server@sha256:45d8b62209fb60889068b3d679dd6d9af0e530516e46752a5f7c82a0bbb5366d
imageTag: proton-latest
# serviceType should be LoadBalancer or NodePort
service:
  type: LoadBalancer
  loadBalancerIP: 10.0.1.129
resources:
  requests:
    memory: 12G
    cpu: 4.0
volumes:
  dataPVC:
    size: 20Gi
  storageClassName: "ssd"
env:
  serverName: 'rwx'
  gamePort: 15636
  queryPort: 15637
  serverSlots: 16
