apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./manifests/serviceaccount.admission-webhook.yaml
  - ./manifests/service.admission-webhook.yaml
  - ./manifests/certificate.admission-webhook.yaml
  - ./manifests/deployment.admission-webhook.yaml
  - ./manifests/validatingwebhookconfiguration.yaml
  - ./manifests/mutatingwebhookconfiguration.yaml
