---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mumble.fullname" . }}-data
  labels:
    {{- include "mumble.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
