---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mumble.fullname" . }}
  labels:
    {{- include "mumble.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  externalTrafficPolicy: Local
  ports:
  - port: {{ .Values.service.port }}
    targetPort: mumble
    protocol: TCP
    name: mumble
  - port: {{ .Values.service.port }}
    targetPort: mumble-udp
    protocol: UDP
    name: mumble-udp
  selector:
    {{- include "mumble.selectorLabels" . | nindent 4 }}
