---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rwx-im
spec:
  secretName: irwx-im-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - rwx.im
