---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: rwx
data:
  postgres.conf: |
    # Replication configs
    listen_addresses = '*'
    max_wal_senders = 10
    max_connections = 100
    shared_buffers = 128MB
    archive_mode = on
    archive_command = '/opt/postgres_archive.sh %p'

  backup_database.sh: |
    #!/usr/bin/env bash
    set -e

    export PGUSER=postgres
    export PGPASSWORD="${POSTGRES_PASSWORD}"

    wal-g backup-push "${PGDATA}"
