apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-auth
  namespace: influxdb
spec:
  encryptedData:
    admin-password: AgB4bfvZxen+MEmjUSf0gG/eFtk0MkfBSDvGa6MR7g4wn6PswjU4MuHmSpfHNodFJBXrztTm96vVxMJ3KAiJAwmWI5uHe9wxeNW00S5kB4MsVKKEng4XWrqxY+iMFc5lLemT2dg0j84XwsmHa75t0oY7AlNtEFrbqhrfE+L/2z7PWvC5zzotF2jpisBjdvSEX6hAOMlnAam6Ts6YUA5an8d6UAikp8hWeCWcegxQq6UzdcRihN03IsrlWzF0ZlfxZiV7fHsUgu8409gBKjg7KEZrTc8SNl7hfcMwkV+o8Tt67PIfliD2VGciaxooXSGdEeoJ6ShsNinao/mKp+B/qUZ0+TRCUZVlVYu7nugOgRr1oExEn3356pfCsIM+ZpfXSjmpleanXKBxjGS7yW79yKh3MEL1vssw8GIKwLS5n6Th8kDgog8SvNt25+VHGlQfjwOMIxfvY+/V8rdayoVeIVCNyOZZRU+Oo/4r2xiECrxmiexRh6vrjecXtr0FATtBI2T+Rt/kMuIGiWRpwYJBIyOQWDyNe2KBN8WNQ++Cyy+DXDFKnkQAi9qfh3A/6hq65sM3KR+z4O1d81P094euMFHJuhkmjubZZeEukGGi/ubRHrVfJl8pctv1Gkhtkt+CbeD/fLFgrWiXNv/P9Z+4ASKmkqUUItAXD92xTgzCr0dxXv9HSYusYh4ekffjBZCiwQGkvtv5+irxrAfTbwRj8LlPWq/qhvtU+4+5xQt1866mt/4PYmaQ1eeaNqoFxDuMN0sDPftNy1QxDBXq6eZERL48
    admin-token: AgCJJGk6gdX4fK4PMgOT5FOB7+3kJ5RvpC3BG433qYhqqBuIBGeYNxajWczmJqIlF8vblfUpAYXhFGWPKgCAtXJJMIp02JnyZPU5UxVqVy1bqMSmyIRFsUBGEKIOJTEUeIbKjq7U8OHSFoOo2lJjuMZAFp7b96h9eLbvT0xFyR0ziz0bDsnelbTafuvA8Yu9c7gJH0P2G+Ban1M6vQhaEhqOwgtWxMgtUxfXS6tjKIH25LDuZ8E7PG5y7iPqbvxQAe2di719gjhkuQVLcQmxD71FDIwHeGejjvDFj4OY3I0SH0oCQMMap0GHU6zdeUidv26Bmyh6BekcqMUjUPrbN/QWU3zzcErW7AUCp5n7/pvdEp97nG+DCGj/qRB6np3GLXYgyaRD2sKpTMsyw+3SYpXmtllQ6vXz94kFK79cm4P9ZLjTMr0Iub0geMvk4CuUGLtEx3ClH/R/RHUvbCrl/3MmaOH7R3ol8kMw8YTFsXURqRWk2C41FCazfANla58cVAoRIJHNbScerhRfomZY2Srqz+xlJisDKZS+pA+0D3EmdRN3GKP/WToA90pbUdAvQ5iPGNRkTRXj4R3IIQij1Y/Dtk+eyipTuD3jVQdSp7446bxejD+1oHJH4UimtJ117SPxf9W+/qA+lIVACCrVJjVui7x2X6TJYfgjhAC8nqPw1GmC4mdYr9QXl2ClhYvC0ygXwfeQn0jYmKUPHIzxqEuT4TWJW2HNiRvUrKM6TPoJYwZeEySXIP+GlUh6dc118H4mlEwGvyaS6LGv06B8Eg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: influxdb-auth
      namespace: influxdb

