apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-auth
  namespace: influxdb
spec:
  encryptedData:
    admin-password: AgAjgGlp3BGpn9a+LB5Ds7gbOigj9O3+xNR34pzOSW3q9D8mJ+QsUBrEG1yCdVC+6lVD9rOvRSLPuPydJi33YBII5XR1PMlouh4GSzQrWE2LdXatbuqvo5Zus3dZaYVCahXocrs4QlmG16pHcJ+SosgNqGTVKz5foZlnnDBG9DaJGyPIaTPWLEmCYruxOSgBrOwkw5RJjCxg7uoGyyst0nuYv99rvXHYaFoh1mf8vSRlMN7s9LVzvxMhMix0T1z/SnCgEHzzrhcvC5UmtyL4HFHuPrRrh+C5OeKNiGZlqlzVCmGiCO4SbcYTRSkC6wGAWduvKu3Eq0mY8+Yu9JT7lgtWyR3HdfCTlEpB5hLUQ9eM9u3eC5yRThtylkZrDkN4LL9unw9NlTyEU/JYe9EHIO0c5HohlbngywJkSIOvUE9xSISWVFuBfrewFSw7wYuh4J2P59IEA5qlMHE8LsRQaVw+iVRVarsUSqJ6s8/8Jd7rjGEGsuYbFCjeIkYSwzEcMfLtnG7hqBXvPLop8tPg8SFyc4o9Cja474A4JXEBYyE7v3T7BK+8HI06o6c2mXMs4ZCkrEJd6SdwS/Ld1VnEVjhhurQ9H4FdsIBrcIaqrtzN1vigBOxz6OlBXuqX+jDSlnIPPAIyeQLldUJNAlfft+0OmxK8JCprSMHCbReNTay6iXa/1zRmn8wIQMD8YQZ7cofTXCytdD+IN0zVNJKquzq3eTdagmEkSYmpFy93NeGp0/0H7/CDyFtusyFSCdTBESLCPWIZV0PXQdg9mjPcPqrC
    admin-token: AgCSDydUCnP6DA1QhVw3mue/qpDlBjG8BJTw1Y4YLk0QXS2Z6Ps1IOpI93DrFYiHRhXGp7ohrO6YyeY5U614v4+TnZlmHsLk8YlTbQBt+w3hO9/ZCrjuvt+eMB990ZnQDb82SIR9XbuclpnGYsVyy8O5m9o+UccwkDaKgYDIyjJplwon/SOeVVaWiI2RN98XK9WGPnxJcsmAqCLf24eEvhNOm3Y2vgsQsMTnVlXGNzOnx10LQsrXKsFlAJHer5jXkeTzpnBsPzWst28D0lOWzPx9icSqq57tHPy2pzFb/ip9M+2tQ0enVprpPlrdk/HZ8wOCAV1tjkRZGKCWMbPLTvUgs7+s0IqXYEH1tP3jQVCRHxhImmVvxFNzj6ztXTaIrJ0UPzTwmHyGUA4Xv4Ffd7Mf4qoATHOxQ4tO+y9pCQd5t9P6S4GRbv+MxjtVgbbSqEKxdykttcS67VdiYL14SdSFPoSsQgoMbNpUxuHMwelp1VP3eFIJVPUHK5wyvrHqxUtgYrhyrtjO7cCYqognK+cr28kVC/kBYEsSy5C/9/D3q7bZ99ehhJt8ppoeT5szl4/eFSKI6LaA6kxs0fbI54IPalAks6Eowx0DQ84Fn1/qVt8TS0QIVKgasAOWCQbfjL8tdL2l9HNa4j/D7Aa3cHhkyWqj9xKEAfxtMrxlA+qqk/Pqwbgx4CI9dKvnI1n4feE9asjtbfaM0EG92qBJbbM7zLDZWsJveyFEjNR6dhU7dXJp+roUKcj29Iveo9gLnkcADx/UJ8pHWR/5/ZFysg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: influxdb-auth
      namespace: influxdb

