apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: influxdb-auth
  namespace: influxdb
spec:
  encryptedData:
    admin-password: AgByasRJknx7XSozXjacvb8L0m2d5lorMa6iB1Zeq4ycMqseTS7iSRZgmvx+056U2wg+i3Lo8Ptf9IC64ug7VmGmrnWynzuMjvJxOiijGdGoEWBgoW8CoYl858DJrK9DjpQFUTO1ftxyqv/BCo17JLsT1hB8fCxyfiyIFSjicnPguW4gZZrlcFV9cu/Lylk+CJIaBfcbs/AkS2YvjoyQauRgpdnpa7uLJ6c2O1gN++pBcG6iq2Jfrkp0ScUp9obTxGm4vMWVnQ0qeugQKNKWl5VG2Z+rr1+Wl/gqx9ewSSwpuDeNaNH8C6Dg3My9IQiPFDP3DRae2njaSRc9rVqw04oK0oleq0oDRXT84cYWQNwwy3HGiJeiD8ma67c1m3+wU4X5D5bm9jWl/WRQ74YNEhEUBnIesfrzHui3Ukvd4Bx9J1TolgU/SzWZFLISLCSvVZT6dNbfkMIFK+4LOlszbkD/W73yQMdPSmYB2RFysOhsTJY371PzrYEoVXxDzEnuDh8CspWkb75Y8w7r6QfGNWr+sHAg2llNHcoqqr1VKDIPHGJTJn/Dl53WvS2gdKaURNNm/0WK/N4Z0fMydz2B63KRwMxlxaSgC6r7I77MhMC/cv0iR/swjFp3xovlUbX6TOJyNwpMEbFl0EK39wIXuiXR6y9qQLHYsEMOKRnOB70DtRuQWWPo2luGV6C+1eQbLsJ2+BuxC4NQO6oz/sGa1iwC49ZA96z4WUtUnoNi0ia0nB8oiv38eo2Z5uNc3JcBzUiedypjiykWgThcZMrcAz6m
    admin-token: AgC8NtE5zz2ZXCullutDu2Hfqz1SslfH4PuswrMQ3I22/PrawQHTbcs7w1MUD6P7cPFp234LmWmAwAroJT2IDbD63JL/tdDW7T82VgeqBJk/uGnmsTQ+odj066QSK+m+sIwAN8jlogFZ771ulFta9pYyd0VhOvwylzT1gCAUmMbGGqEsADwcw0Ji03sajtf48Zwr69tksyXs0/Wnn4voxPVLxtupzRjpBmC4rxMmfqYv8FtTaVlZcupbrt1D6qKNWxHMVNVZU19cuwqGlIhivlWaktRK4i76f+vclOLwPB8bXbtBnlwwrkOppZBSYzeSq7YycsHRSJY+CfS+5pvtbktDUbhYgNdZS0vixZQ6RPt1aJ+bzt3+0Aey9T/SEXbIpH3F+xONqktigsC89O/uHVoRMCRk/n68H0fizHxVxT5AUTKUnTFkJKX+s7indNt93cbg3MZ01Jqt58xh1EEGzVPhBpr546Z3RVqETqbqXgzgxAPWEB4mHBXLU4uIbWx+hRAGdIjJZ/5pSkRL0WtiK2DD0ZXC4B1irPgcv9BCcGrkqe21Zv6In4u1t21X2ck2U1csIw6BTsP1jk9dWTwAywB4/EpYKkhACuxka5XULSx8d2mACzIN7l/t6Yto5MZ7PXeu3xIIOM1iIfUrYtYAElydbTyoQ+ZHFvYdUVLjpJwD3TTkimx/d96Yac6d76kEGhWQl06I27IlWSHaQzAk3EV6X68YzqKw5Cn/Y6r83m4O7u+NIvQJVnHXgVAUpSEZ/JkDSzF+q3C16kuWwV3s5neO
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: influxdb-auth
      namespace: influxdb

