apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-auth
  namespace: rwx
spec:
  encryptedData:
    replicationUserPassword: AgCAnJIPaJaE0svl0roDRfAPE3Fvdu7ND3c0L0BBaxQaM7mmoBLMXPUt5ZgciOWtNt9XIcUfTi9nVWUwR23V43qTk/+JtaZjzfDEZ+EHjy/YMieDkISRgI+ZqY4xowr1Eot8z6MxUJ0PwpxO/1LEqKSPNRjBRac5WipXrU+ecU2k0wCmuT6DwwxmqOmWjC4viUyug4rCaLvoIQCfoG/UghfPMcoKAfPbC3ilYV/DndYHdYcenj9600kjfv/jg30WRvXoqaAM0u4W34qZm8BcNw6VKfc1Y3PnxVg0ffLxEJfisnotNZn1hv7kecoZb1aQ277z+ZFN5OFsH9iyaaoitDmJW0I5I8lKb99/I8oXO+PM5eifVqhLkict699Ms83DeKBLdaXv9J45iuz/bk9glDDQ6kiXN3lSHQShTfwNoQRTavWpFs4Amu9qLptr6TQP7/FSw+If/5FQYrwvWylrYetr83h31/88TWhSH0WaXGCZQHvTMXPwlPfFn1/2ulOScTZhtp2W5vboEatExuV1Z5oGoFw3YLBPCeUx5LumI8aYR2kYT5YDhFVpKQ4ufm8UukzEM8mxTyPIll9FmDL95fRUwrgTQCc6QUnwc2TUPaUr2kPilDOCaxBvJYbymTCzu/moUysf5jOwMjCI3poOzp5Qma1uoNSl+ghPFJLHKXZ01QN7DIGg4e2jMxoQ0wY0ynq1gBIw8LMOlFybUVC7QEcMmt9pQFhlIeCNehPCPzYzOjmJ2BjwcTHuMhDVMWICVw9YIjo36zm8V8MgOsD+
    superUserPassword: AgCqlmxPI4oBOnjhp0u2ZwXbRjWJWOqYhQ8SJ0Rhr/Ul81JsCEnV3dFgKhT1F/J4/TE5qdcQvF+/XgdwX3KLfPdk4oslj03SBMUdrI+znVcEVgyyRLazFGZoUQ7FFc44KQoF46wk9F6Xr/lS6HbkXzxvKyAz1mBPXqg4ppsfcog3jfy7cZmBTxn6vexbhYls8Ic2TwzmxVyy9v86q39VNHAjA1Hp4YwGsAXq2QSijvt4pWMyAg+0QFexV+gP+oHCiUamQX6IszT47JO2G58IEnAV1vtSqpaxIcAnNsUT3r8Sivbff6pRNSFBSIW6HGlZ8/p6BqfA4/m9+SKAtnfn683yvTcV+G5xJLcw/3II3DN5TjpyEMQ79jfcl9T9hm1gUFJdJN/90C0oAOaNe3a5wBJUp2TnLSvqbO4kRTMiFcttspbncve+jUPo+TmJ988z61sf7O3uwV2Qe/60Vpv8OKoZCneu7Z2CZDb19ivBZiN0hfgzJ1NZ2vs0Cz/g/5k7q21yTON5OsvTa+zxaDkDlcZItJIwrPcaCYTdeeoasx6VyMyXcnWS6FV8OgRCTxUbZTK57ELUNpwZ76SXIw4rJubgnNesZrnUWJHvZ4ogHS/xlVFzSnCHCPQQNwdjfBgck/jfBAQ2pyuhyLJZ0kHRWvX/G2T2W6EVhCstyeQSGS6Qi5xXOQfHPCqbNia1ZVblnPfiuqElgYEqb1EeRxThxl106rI391OwIX2a7+CLMTazmhCGhSgfo9/c1Faq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-auth
      namespace: rwx
    type: Opaque

