---
name: Lint

on: [push, pull_request]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Lint and Annotate
      uses: staffbase/yamllint-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ## The target path is processed recursively
        target-path: .
