quickwit:
  environment:
    QW_DISABLE_TELEMETRY: 1
  environmentFrom:
    - secretRef:
        name: quickwit

  searcher:
    replicaCount: 3

  indexer:
    replicaCount: 1

  metastore:
    replicaCount: 1

    extraEnvFrom:
      - secretRef:
          name: quickwit-metastore

  # Quickwit configuration
  #
  # Warning: This config is writed directly into a configMap
  # to avoid passing sensitive value you can pass environment variables.
  # https://quickwit.io/docs/configuration/node-config#using-environment-variables-in-the-configuration
  config:
    version: 0.8
    listen_address: 0.0.0.0
    gossip_listen_port: 7282
    data_dir: /quickwit/qwdata
    default_index_root_uri: s3://quickwit-prod/indexes

    metastore:
      postgres:
        max_num_connections: 50

    storage:
      s3:
        endpoint: "https://s3.eu-central-003.backblazeb2.com"
        region: "eu-central-003"

  # Deploy the ServiceMonitor so we can pick up metrics.
  serviceMonitor:
    enabled: true
    additionalLabels:
      metrics.uplink.io/monitor: prometheus

  prometheusRule:
    # -- Create the provided prometheus rule resources.
    enabled: true

    rules:
      - alert: QuickwitSustainedHighThroughput
        # Calculates the per-second rate of successfully processed documents
        # over a 5-minute window, summed by index. Change "100" to a baseline
        # that makes sense for your cluster's standard volume.
        expr: sum by (index)
          (rate(quickwit_indexing_processed_docs_total{docs_processed_status="valid"}[5m])) > 100

        # The condition must be continuously met for 30 minutes before firing.
        for: 30m

        labels:
          severity: warning # Route this label in Alertmanager to your preferred channel
        annotations:
          summary: "Sustained high document throughput on Quickwit index '{{ $labels.index }}'"
          description: >-
            The Quickwit index '{{ $labels.index }}' has experienced a sustained indexing throughput
            of over 100 docs/sec for more than 30 minutes.  Current rate is {{ $value | humanize }}
            docs/sec.
